// --- Types ---
export interface Seat {
  row: string;
  seatNumber: number;
  x: number;
  y: number;
}

export interface TierLayout {
  rows: number;
  columns: number;
  seats: Seat[];
}

export interface SectionedSeatsLayout {
  vip: TierLayout;
  premium: TierLayout;
  standard: TierLayout;
}

export const seatsLayout: SectionedSeatsLayout = {
  standard: {
    rows: 20,
    columns: 30,
    seats: [
      { row: "A", seatNumber: 5, x: 4, y: 0 },
      { row: "A", seatNumber: 6, x: 5, y: 0 },
      { row: "A", seatNumber: 7, x: 6, y: 0 },
      { row: "A", seatNumber: 8, x: 7, y: 0 },
      { row: "A", seatNumber: 9, x: 8, y: 0 },
      { row: "A", seatNumber: 10, x: 9, y: 0 },
      { row: "A", seatNumber: 11, x: 10, y: 0 },
      { row: "A", seatNumber: 12, x: 11, y: 0 },
      { row: "A", seatNumber: 13, x: 12, y: 0 },
      { row: "A", seatNumber: 14, x: 13, y: 0 },
      { row: "A", seatNumber: 17, x: 16, y: 0 },
      { row: "A", seatNumber: 18, x: 17, y: 0 },
      { row: "A", seatNumber: 19, x: 18, y: 0 },
      { row: "A", seatNumber: 20, x: 19, y: 0 },
      { row: "A", seatNumber: 21, x: 20, y: 0 },
      { row: "A", seatNumber: 22, x: 21, y: 0 },
      { row: "A", seatNumber: 23, x: 22, y: 0 },
      { row: "A", seatNumber: 24, x: 23, y: 0 },
      { row: "A", seatNumber: 25, x: 24, y: 0 },
      { row: "A", seatNumber: 26, x: 25, y: 0 },
      { row: "B", seatNumber: 5, x: 4, y: 1 },
      { row: "B", seatNumber: 6, x: 5, y: 1 },
      { row: "B", seatNumber: 7, x: 6, y: 1 },
      { row: "B", seatNumber: 8, x: 7, y: 1 },
      { row: "B", seatNumber: 9, x: 8, y: 1 },
      { row: "B", seatNumber: 10, x: 9, y: 1 },
      { row: "B", seatNumber: 11, x: 10, y: 1 },
      { row: "B", seatNumber: 12, x: 11, y: 1 },
      { row: "B", seatNumber: 13, x: 12, y: 1 },
      { row: "B", seatNumber: 14, x: 13, y: 1 },
      { row: "B", seatNumber: 17, x: 16, y: 1 },
      { row: "B", seatNumber: 18, x: 17, y: 1 },
      { row: "B", seatNumber: 19, x: 18, y: 1 },
      { row: "B", seatNumber: 20, x: 19, y: 1 },
      { row: "B", seatNumber: 21, x: 20, y: 1 },
      { row: "B", seatNumber: 22, x: 21, y: 1 },
      { row: "B", seatNumber: 23, x: 22, y: 1 },
      { row: "B", seatNumber: 24, x: 23, y: 1 },
      { row: "B", seatNumber: 25, x: 24, y: 1 },
      { row: "B", seatNumber: 26, x: 25, y: 1 },
      { row: "B", seatNumber: 27, x: 26, y: 1 },
      { row: "C", seatNumber: 4, x: 3, y: 2 },
      { row: "C", seatNumber: 5, x: 4, y: 2 },
      { row: "C", seatNumber: 6, x: 5, y: 2 },
      { row: "C", seatNumber: 7, x: 6, y: 2 },
      { row: "C", seatNumber: 8, x: 7, y: 2 },
      { row: "C", seatNumber: 9, x: 8, y: 2 },
      { row: "C", seatNumber: 10, x: 9, y: 2 },
      { row: "C", seatNumber: 11, x: 10, y: 2 },
      { row: "C", seatNumber: 12, x: 11, y: 2 },
      { row: "C", seatNumber: 13, x: 12, y: 2 },
      { row: "C", seatNumber: 14, x: 13, y: 2 },
      { row: "C", seatNumber: 17, x: 16, y: 2 },
      { row: "C", seatNumber: 18, x: 17, y: 2 },
      { row: "C", seatNumber: 19, x: 18, y: 2 },
      { row: "C", seatNumber: 20, x: 19, y: 2 },
      { row: "C", seatNumber: 21, x: 20, y: 2 },
      { row: "C", seatNumber: 22, x: 21, y: 2 },
      { row: "C", seatNumber: 23, x: 22, y: 2 },
      { row: "C", seatNumber: 24, x: 23, y: 2 },
      { row: "C", seatNumber: 25, x: 24, y: 2 },
      { row: "C", seatNumber: 26, x: 25, y: 2 },
      { row: "C", seatNumber: 27, x: 26, y: 2 },
      { row: "C", seatNumber: 28, x: 27, y: 2 },
      { row: "D", seatNumber: 3, x: 2, y: 3 },
      { row: "D", seatNumber: 4, x: 3, y: 3 },
      { row: "D", seatNumber: 5, x: 4, y: 3 },
      { row: "D", seatNumber: 6, x: 5, y: 3 },
      { row: "D", seatNumber: 7, x: 6, y: 3 },
      { row: "D", seatNumber: 8, x: 7, y: 3 },
      { row: "D", seatNumber: 9, x: 8, y: 3 },
      { row: "D", seatNumber: 10, x: 9, y: 3 },
      { row: "D", seatNumber: 11, x: 10, y: 3 },
      { row: "D", seatNumber: 12, x: 11, y: 3 },
      { row: "D", seatNumber: 13, x: 12, y: 3 },
      { row: "D", seatNumber: 14, x: 13, y: 3 },
      { row: "D", seatNumber: 17, x: 16, y: 3 },
      { row: "D", seatNumber: 18, x: 17, y: 3 },
      { row: "D", seatNumber: 19, x: 18, y: 3 },
      { row: "D", seatNumber: 20, x: 19, y: 3 },
      { row: "D", seatNumber: 21, x: 20, y: 3 },
      { row: "D", seatNumber: 22, x: 21, y: 3 },
      { row: "D", seatNumber: 23, x: 22, y: 3 },
      { row: "D", seatNumber: 24, x: 23, y: 3 },
      { row: "D", seatNumber: 25, x: 24, y: 3 },
      { row: "D", seatNumber: 26, x: 25, y: 3 },
      { row: "D", seatNumber: 27, x: 26, y: 3 },
      { row: "D", seatNumber: 28, x: 27, y: 3 },
      { row: "D", seatNumber: 29, x: 28, y: 3 },
      { row: "D", seatNumber: 30, x: 29, y: 3 },
      { row: "E", seatNumber: 1, x: 0, y: 4 },
      { row: "E", seatNumber: 2, x: 1, y: 4 },
      { row: "E", seatNumber: 3, x: 2, y: 4 },
      { row: "E", seatNumber: 4, x: 3, y: 4 },
      { row: "E", seatNumber: 5, x: 4, y: 4 },
      { row: "E", seatNumber: 6, x: 5, y: 4 },
      { row: "E", seatNumber: 7, x: 6, y: 4 },
      { row: "E", seatNumber: 8, x: 7, y: 4 },
      { row: "E", seatNumber: 9, x: 8, y: 4 },
      { row: "E", seatNumber: 10, x: 9, y: 4 },
      { row: "E", seatNumber: 11, x: 10, y: 4 },
      { row: "E", seatNumber: 12, x: 11, y: 4 },
      { row: "E", seatNumber: 13, x: 12, y: 4 },
      { row: "E", seatNumber: 14, x: 13, y: 4 },
      { row: "E", seatNumber: 17, x: 16, y: 4 },
      { row: "E", seatNumber: 18, x: 17, y: 4 },
      { row: "E", seatNumber: 19, x: 18, y: 4 },
      { row: "E", seatNumber: 20, x: 19, y: 4 },
      { row: "E", seatNumber: 21, x: 20, y: 4 },
      { row: "E", seatNumber: 22, x: 21, y: 4 },
      { row: "E", seatNumber: 23, x: 22, y: 4 },
      { row: "E", seatNumber: 24, x: 23, y: 4 },
      { row: "E", seatNumber: 25, x: 24, y: 4 },
      { row: "E", seatNumber: 26, x: 25, y: 4 },
      { row: "E", seatNumber: 27, x: 26, y: 4 },
      { row: "E", seatNumber: 28, x: 27, y: 4 },
      { row: "E", seatNumber: 29, x: 28, y: 4 },
      { row: "E", seatNumber: 30, x: 29, y: 4 },
      { row: "F", seatNumber: 1, x: 0, y: 5 },
      { row: "F", seatNumber: 2, x: 1, y: 5 },
      { row: "F", seatNumber: 3, x: 2, y: 5 },
      { row: "F", seatNumber: 4, x: 3, y: 5 },
      { row: "F", seatNumber: 5, x: 4, y: 5 },
      { row: "F", seatNumber: 6, x: 5, y: 5 },
      { row: "F", seatNumber: 7, x: 6, y: 5 },
      { row: "F", seatNumber: 8, x: 7, y: 5 },
      { row: "F", seatNumber: 9, x: 8, y: 5 },
      { row: "F", seatNumber: 10, x: 9, y: 5 },
      { row: "F", seatNumber: 11, x: 10, y: 5 },
      { row: "F", seatNumber: 12, x: 11, y: 5 },
      { row: "F", seatNumber: 13, x: 12, y: 5 },
      { row: "F", seatNumber: 14, x: 13, y: 5 },
      { row: "F", seatNumber: 17, x: 16, y: 5 },
      { row: "F", seatNumber: 18, x: 17, y: 5 },
      { row: "F", seatNumber: 19, x: 18, y: 5 },
      { row: "F", seatNumber: 20, x: 19, y: 5 },
      { row: "F", seatNumber: 21, x: 20, y: 5 },
      { row: "F", seatNumber: 22, x: 21, y: 5 },
      { row: "F", seatNumber: 23, x: 22, y: 5 },
      { row: "F", seatNumber: 24, x: 23, y: 5 },
      { row: "F", seatNumber: 25, x: 24, y: 5 },
      { row: "F", seatNumber: 26, x: 25, y: 5 },
      { row: "F", seatNumber: 27, x: 26, y: 5 },
      { row: "F", seatNumber: 28, x: 27, y: 5 },
      { row: "F", seatNumber: 29, x: 28, y: 5 },
      { row: "F", seatNumber: 30, x: 29, y: 5 },
      { row: "G", seatNumber: 1, x: 0, y: 6 },
      { row: "G", seatNumber: 2, x: 1, y: 6 },
      { row: "G", seatNumber: 3, x: 2, y: 6 },
      { row: "G", seatNumber: 4, x: 3, y: 6 },
      { row: "G", seatNumber: 5, x: 4, y: 6 },
      { row: "G", seatNumber: 6, x: 5, y: 6 },
      { row: "G", seatNumber: 7, x: 6, y: 6 },
      { row: "G", seatNumber: 8, x: 7, y: 6 },
      { row: "G", seatNumber: 9, x: 8, y: 6 },
      { row: "G", seatNumber: 10, x: 9, y: 6 },
      { row: "G", seatNumber: 11, x: 10, y: 6 },
      { row: "G", seatNumber: 12, x: 11, y: 6 },
      { row: "G", seatNumber: 13, x: 12, y: 6 },
      { row: "G", seatNumber: 14, x: 13, y: 6 },
      { row: "G", seatNumber: 17, x: 16, y: 6 },
      { row: "G", seatNumber: 18, x: 17, y: 6 },
      { row: "G", seatNumber: 19, x: 18, y: 6 },
      { row: "G", seatNumber: 20, x: 19, y: 6 },
      { row: "G", seatNumber: 21, x: 20, y: 6 },
      { row: "G", seatNumber: 22, x: 21, y: 6 },
      { row: "G", seatNumber: 23, x: 22, y: 6 },
      { row: "G", seatNumber: 24, x: 23, y: 6 },
      { row: "G", seatNumber: 25, x: 24, y: 6 },
      { row: "G", seatNumber: 26, x: 25, y: 6 },
      { row: "G", seatNumber: 27, x: 26, y: 6 },
      { row: "G", seatNumber: 28, x: 27, y: 6 },
      { row: "G", seatNumber: 29, x: 28, y: 6 },
      { row: "G", seatNumber: 30, x: 29, y: 6 },
      { row: "H", seatNumber: 1, x: 0, y: 7 },
      { row: "H", seatNumber: 2, x: 1, y: 7 },
      { row: "H", seatNumber: 3, x: 2, y: 7 },
      { row: "H", seatNumber: 4, x: 3, y: 7 },
      { row: "H", seatNumber: 5, x: 4, y: 7 },
      { row: "H", seatNumber: 6, x: 5, y: 7 },
      { row: "H", seatNumber: 7, x: 6, y: 7 },
      { row: "H", seatNumber: 8, x: 7, y: 7 },
      { row: "H", seatNumber: 9, x: 8, y: 7 },
      { row: "H", seatNumber: 10, x: 9, y: 7 },
      { row: "H", seatNumber: 11, x: 10, y: 7 },
      { row: "H", seatNumber: 12, x: 11, y: 7 },
      { row: "H", seatNumber: 13, x: 12, y: 7 },
      { row: "H", seatNumber: 14, x: 13, y: 7 },
      { row: "H", seatNumber: 17, x: 16, y: 7 },
      { row: "H", seatNumber: 18, x: 17, y: 7 },
      { row: "H", seatNumber: 19, x: 18, y: 7 },
      { row: "H", seatNumber: 20, x: 19, y: 7 },
      { row: "H", seatNumber: 21, x: 20, y: 7 },
      { row: "H", seatNumber: 22, x: 21, y: 7 },
      { row: "H", seatNumber: 23, x: 22, y: 7 },
      { row: "H", seatNumber: 24, x: 23, y: 7 },
      { row: "H", seatNumber: 25, x: 24, y: 7 },
      { row: "H", seatNumber: 26, x: 25, y: 7 },
      { row: "H", seatNumber: 27, x: 26, y: 7 },
      { row: "H", seatNumber: 28, x: 27, y: 7 },
      { row: "H", seatNumber: 29, x: 28, y: 7 },
      { row: "H", seatNumber: 30, x: 29, y: 7 },
      { row: "K", seatNumber: 1, x: 0, y: 10 },
      { row: "K", seatNumber: 2, x: 1, y: 10 },
      { row: "K", seatNumber: 3, x: 2, y: 10 },
      { row: "K", seatNumber: 4, x: 3, y: 10 },
      { row: "K", seatNumber: 5, x: 4, y: 10 },
      { row: "K", seatNumber: 6, x: 5, y: 10 },
      { row: "K", seatNumber: 7, x: 6, y: 10 },
      { row: "K", seatNumber: 8, x: 7, y: 10 },
      { row: "K", seatNumber: 9, x: 8, y: 10 },
      { row: "K", seatNumber: 10, x: 9, y: 10 },
      { row: "K", seatNumber: 11, x: 10, y: 10 },
      { row: "K", seatNumber: 12, x: 11, y: 10 },
      { row: "K", seatNumber: 13, x: 12, y: 10 },
      { row: "K", seatNumber: 14, x: 13, y: 10 },
      { row: "K", seatNumber: 17, x: 16, y: 10 },
      { row: "K", seatNumber: 18, x: 17, y: 10 },
      { row: "K", seatNumber: 19, x: 18, y: 10 },
      { row: "K", seatNumber: 20, x: 19, y: 10 },
      { row: "K", seatNumber: 21, x: 20, y: 10 },
      { row: "K", seatNumber: 22, x: 21, y: 10 },
      { row: "K", seatNumber: 23, x: 22, y: 10 },
      { row: "K", seatNumber: 24, x: 23, y: 10 },
      { row: "K", seatNumber: 25, x: 24, y: 10 },
      { row: "K", seatNumber: 26, x: 25, y: 10 },
      { row: "K", seatNumber: 27, x: 26, y: 10 },
      { row: "K", seatNumber: 28, x: 27, y: 10 },
      { row: "K", seatNumber: 29, x: 28, y: 10 },
      { row: "K", seatNumber: 30, x: 29, y: 10 },
      { row: "L", seatNumber: 1, x: 0, y: 11 },
      { row: "L", seatNumber: 2, x: 1, y: 11 },
      { row: "L", seatNumber: 3, x: 2, y: 11 },
      { row: "L", seatNumber: 4, x: 3, y: 11 },
      { row: "L", seatNumber: 5, x: 4, y: 11 },
      { row: "L", seatNumber: 6, x: 5, y: 11 },
      { row: "L", seatNumber: 7, x: 6, y: 11 },
      { row: "L", seatNumber: 8, x: 7, y: 11 },
      { row: "L", seatNumber: 9, x: 8, y: 11 },
      { row: "L", seatNumber: 10, x: 9, y: 11 },
      { row: "L", seatNumber: 11, x: 10, y: 11 },
      { row: "L", seatNumber: 12, x: 11, y: 11 },
      { row: "L", seatNumber: 13, x: 12, y: 11 },
      { row: "L", seatNumber: 14, x: 13, y: 11 },
      { row: "L", seatNumber: 17, x: 16, y: 11 },
      { row: "L", seatNumber: 18, x: 17, y: 11 },
      { row: "L", seatNumber: 19, x: 18, y: 11 },
      { row: "L", seatNumber: 20, x: 19, y: 11 },
      { row: "L", seatNumber: 21, x: 20, y: 11 },
      { row: "L", seatNumber: 22, x: 21, y: 11 },
      { row: "L", seatNumber: 23, x: 22, y: 11 },
      { row: "L", seatNumber: 24, x: 23, y: 11 },
      { row: "L", seatNumber: 25, x: 24, y: 11 },
      { row: "L", seatNumber: 26, x: 25, y: 11 },
      { row: "L", seatNumber: 27, x: 26, y: 11 },
      { row: "L", seatNumber: 28, x: 27, y: 11 },
      { row: "L", seatNumber: 29, x: 28, y: 11 },
      { row: "L", seatNumber: 30, x: 29, y: 11 },
      { row: "M", seatNumber: 1, x: 0, y: 12 },
      { row: "M", seatNumber: 2, x: 1, y: 12 },
      { row: "M", seatNumber: 3, x: 2, y: 12 },
      { row: "M", seatNumber: 4, x: 3, y: 12 },
      { row: "M", seatNumber: 5, x: 4, y: 12 },
      { row: "M", seatNumber: 6, x: 5, y: 12 },
      { row: "M", seatNumber: 7, x: 6, y: 12 },
      { row: "M", seatNumber: 8, x: 7, y: 12 },
      { row: "M", seatNumber: 9, x: 8, y: 12 },
      { row: "M", seatNumber: 10, x: 9, y: 12 },
      { row: "M", seatNumber: 11, x: 10, y: 12 },
      { row: "M", seatNumber: 12, x: 11, y: 12 },
      { row: "M", seatNumber: 13, x: 12, y: 12 },
      { row: "M", seatNumber: 14, x: 13, y: 12 },
      { row: "M", seatNumber: 17, x: 16, y: 12 },
      { row: "M", seatNumber: 18, x: 17, y: 12 },
      { row: "M", seatNumber: 19, x: 18, y: 12 },
      { row: "M", seatNumber: 20, x: 19, y: 12 },
      { row: "M", seatNumber: 21, x: 20, y: 12 },
      { row: "M", seatNumber: 22, x: 21, y: 12 },
      { row: "M", seatNumber: 23, x: 22, y: 12 },
      { row: "M", seatNumber: 24, x: 23, y: 12 },
      { row: "M", seatNumber: 25, x: 24, y: 12 },
      { row: "M", seatNumber: 26, x: 25, y: 12 },
      { row: "M", seatNumber: 27, x: 26, y: 12 },
      { row: "M", seatNumber: 28, x: 27, y: 12 },
      { row: "M", seatNumber: 29, x: 28, y: 12 },
      { row: "M", seatNumber: 30, x: 29, y: 12 },
      { row: "N", seatNumber: 1, x: 0, y: 13 },
      { row: "N", seatNumber: 2, x: 1, y: 13 },
      { row: "N", seatNumber: 3, x: 2, y: 13 },
      { row: "N", seatNumber: 4, x: 3, y: 13 },
      { row: "N", seatNumber: 5, x: 4, y: 13 },
      { row: "N", seatNumber: 6, x: 5, y: 13 },
      { row: "N", seatNumber: 7, x: 6, y: 13 },
      { row: "N", seatNumber: 8, x: 7, y: 13 },
      { row: "N", seatNumber: 9, x: 8, y: 13 },
      { row: "N", seatNumber: 10, x: 9, y: 13 },
      { row: "N", seatNumber: 11, x: 10, y: 13 },
      { row: "N", seatNumber: 12, x: 11, y: 13 },
      { row: "N", seatNumber: 13, x: 12, y: 13 },
      { row: "N", seatNumber: 14, x: 13, y: 13 },
      { row: "N", seatNumber: 17, x: 16, y: 13 },
      { row: "N", seatNumber: 18, x: 17, y: 13 },
      { row: "N", seatNumber: 19, x: 18, y: 13 },
      { row: "N", seatNumber: 20, x: 19, y: 13 },
      { row: "N", seatNumber: 21, x: 20, y: 13 },
      { row: "N", seatNumber: 22, x: 21, y: 13 },
      { row: "N", seatNumber: 23, x: 22, y: 13 },
      { row: "N", seatNumber: 24, x: 23, y: 13 },
      { row: "N", seatNumber: 25, x: 24, y: 13 },
      { row: "N", seatNumber: 26, x: 25, y: 13 },
      { row: "N", seatNumber: 27, x: 26, y: 13 },
      { row: "N", seatNumber: 28, x: 27, y: 13 },
      { row: "N", seatNumber: 29, x: 28, y: 13 },
      { row: "N", seatNumber: 30, x: 29, y: 13 },
      { row: "O", seatNumber: 1, x: 0, y: 14 },
      { row: "O", seatNumber: 2, x: 1, y: 14 },
      { row: "O", seatNumber: 3, x: 2, y: 14 },
      { row: "O", seatNumber: 4, x: 3, y: 14 },
      { row: "O", seatNumber: 5, x: 4, y: 14 },
      { row: "O", seatNumber: 6, x: 5, y: 14 },
      { row: "O", seatNumber: 7, x: 6, y: 14 },
      { row: "O", seatNumber: 8, x: 7, y: 14 },
      { row: "O", seatNumber: 9, x: 8, y: 14 },
      { row: "O", seatNumber: 10, x: 9, y: 14 },
      { row: "O", seatNumber: 11, x: 10, y: 14 },
      { row: "O", seatNumber: 12, x: 11, y: 14 },
      { row: "O", seatNumber: 13, x: 12, y: 14 },
      { row: "O", seatNumber: 14, x: 13, y: 14 },
      { row: "O", seatNumber: 17, x: 16, y: 14 },
      { row: "O", seatNumber: 18, x: 17, y: 14 },
      { row: "O", seatNumber: 19, x: 18, y: 14 },
      { row: "O", seatNumber: 20, x: 19, y: 14 },
      { row: "O", seatNumber: 21, x: 20, y: 14 },
      { row: "O", seatNumber: 22, x: 21, y: 14 },
      { row: "O", seatNumber: 23, x: 22, y: 14 },
      { row: "O", seatNumber: 24, x: 23, y: 14 },
      { row: "O", seatNumber: 25, x: 24, y: 14 },
      { row: "O", seatNumber: 26, x: 25, y: 14 },
      { row: "O", seatNumber: 27, x: 26, y: 14 },
      { row: "O", seatNumber: 28, x: 27, y: 14 },
      { row: "O", seatNumber: 29, x: 28, y: 14 },
      { row: "O", seatNumber: 30, x: 29, y: 14 },
      { row: "P", seatNumber: 1, x: 0, y: 15 },
      { row: "P", seatNumber: 2, x: 1, y: 15 },
      { row: "P", seatNumber: 3, x: 2, y: 15 },
      { row: "P", seatNumber: 4, x: 3, y: 15 },
      { row: "P", seatNumber: 5, x: 4, y: 15 },
      { row: "P", seatNumber: 6, x: 5, y: 15 },
      { row: "P", seatNumber: 7, x: 6, y: 15 },
      { row: "P", seatNumber: 8, x: 7, y: 15 },
      { row: "P", seatNumber: 9, x: 8, y: 15 },
      { row: "P", seatNumber: 10, x: 9, y: 15 },
      { row: "P", seatNumber: 11, x: 10, y: 15 },
      { row: "P", seatNumber: 12, x: 11, y: 15 },
      { row: "P", seatNumber: 13, x: 12, y: 15 },
      { row: "P", seatNumber: 14, x: 13, y: 15 },
      { row: "P", seatNumber: 17, x: 16, y: 15 },
      { row: "P", seatNumber: 18, x: 17, y: 15 },
      { row: "P", seatNumber: 19, x: 18, y: 15 },
      { row: "P", seatNumber: 20, x: 19, y: 15 },
      { row: "P", seatNumber: 21, x: 20, y: 15 },
      { row: "P", seatNumber: 22, x: 21, y: 15 },
      { row: "P", seatNumber: 23, x: 22, y: 15 },
      { row: "P", seatNumber: 24, x: 23, y: 15 },
      { row: "P", seatNumber: 25, x: 24, y: 15 },
      { row: "P", seatNumber: 26, x: 25, y: 15 },
      { row: "P", seatNumber: 27, x: 26, y: 15 },
      { row: "P", seatNumber: 28, x: 27, y: 15 },
      { row: "P", seatNumber: 29, x: 28, y: 15 },
      { row: "P", seatNumber: 30, x: 29, y: 15 },
      { row: "Q", seatNumber: 1, x: 0, y: 16 },
      { row: "Q", seatNumber: 2, x: 1, y: 16 },
      { row: "Q", seatNumber: 3, x: 2, y: 16 },
      { row: "Q", seatNumber: 4, x: 3, y: 16 },
      { row: "Q", seatNumber: 5, x: 4, y: 16 },
      { row: "Q", seatNumber: 6, x: 5, y: 16 },
      { row: "Q", seatNumber: 7, x: 6, y: 16 },
      { row: "Q", seatNumber: 8, x: 7, y: 16 },
      { row: "Q", seatNumber: 9, x: 8, y: 16 },
      { row: "Q", seatNumber: 10, x: 9, y: 16 },
      { row: "Q", seatNumber: 11, x: 10, y: 16 },
      { row: "Q", seatNumber: 12, x: 11, y: 16 },
      { row: "Q", seatNumber: 13, x: 12, y: 16 },
      { row: "Q", seatNumber: 14, x: 13, y: 16 },
      { row: "Q", seatNumber: 17, x: 16, y: 16 },
      { row: "Q", seatNumber: 18, x: 17, y: 16 },
      { row: "Q", seatNumber: 19, x: 18, y: 16 },
      { row: "Q", seatNumber: 20, x: 19, y: 16 },
      { row: "Q", seatNumber: 21, x: 20, y: 16 },
      { row: "Q", seatNumber: 22, x: 21, y: 16 },
      { row: "Q", seatNumber: 23, x: 22, y: 16 },
      { row: "Q", seatNumber: 24, x: 23, y: 16 },
      { row: "Q", seatNumber: 25, x: 24, y: 16 },
      { row: "Q", seatNumber: 26, x: 25, y: 16 },
      { row: "Q", seatNumber: 27, x: 26, y: 16 },
      { row: "Q", seatNumber: 28, x: 27, y: 16 },
      { row: "Q", seatNumber: 29, x: 28, y: 16 },
      { row: "Q", seatNumber: 30, x: 29, y: 16 },
      { row: "R", seatNumber: 1, x: 0, y: 17 },
      { row: "R", seatNumber: 2, x: 1, y: 17 },
      { row: "R", seatNumber: 3, x: 2, y: 17 },
      { row: "R", seatNumber: 4, x: 3, y: 17 },
      { row: "R", seatNumber: 5, x: 4, y: 17 },
      { row: "R", seatNumber: 6, x: 5, y: 17 },
      { row: "R", seatNumber: 7, x: 6, y: 17 },
      { row: "R", seatNumber: 8, x: 7, y: 17 },
      { row: "R", seatNumber: 9, x: 8, y: 17 },
      { row: "R", seatNumber: 10, x: 9, y: 17 },
      { row: "R", seatNumber: 11, x: 10, y: 17 },
      { row: "R", seatNumber: 12, x: 11, y: 17 },
      { row: "R", seatNumber: 13, x: 12, y: 17 },
      { row: "R", seatNumber: 14, x: 13, y: 17 },
      { row: "R", seatNumber: 17, x: 16, y: 17 },
      { row: "R", seatNumber: 18, x: 17, y: 17 },
      { row: "R", seatNumber: 19, x: 18, y: 17 },
      { row: "R", seatNumber: 20, x: 19, y: 17 },
      { row: "R", seatNumber: 21, x: 20, y: 17 },
      { row: "R", seatNumber: 22, x: 21, y: 17 },
      { row: "R", seatNumber: 23, x: 22, y: 17 },
      { row: "R", seatNumber: 24, x: 23, y: 17 },
      { row: "R", seatNumber: 25, x: 24, y: 17 },
      { row: "R", seatNumber: 26, x: 25, y: 17 },
      { row: "R", seatNumber: 27, x: 26, y: 17 },
      { row: "R", seatNumber: 28, x: 27, y: 17 },
      { row: "R", seatNumber: 29, x: 28, y: 17 },
      { row: "R", seatNumber: 30, x: 29, y: 17 },
      { row: "S", seatNumber: 1, x: 0, y: 18 },
      { row: "S", seatNumber: 2, x: 1, y: 18 },
      { row: "S", seatNumber: 3, x: 2, y: 18 },
      { row: "S", seatNumber: 4, x: 3, y: 18 },
      { row: "S", seatNumber: 5, x: 4, y: 18 },
      { row: "S", seatNumber: 6, x: 5, y: 18 },
      { row: "S", seatNumber: 7, x: 6, y: 18 },
      { row: "S", seatNumber: 8, x: 7, y: 18 },
      { row: "S", seatNumber: 9, x: 8, y: 18 },
      { row: "S", seatNumber: 10, x: 9, y: 18 },
      { row: "S", seatNumber: 11, x: 10, y: 18 },
      { row: "S", seatNumber: 12, x: 11, y: 18 },
      { row: "S", seatNumber: 13, x: 12, y: 18 },
      { row: "S", seatNumber: 14, x: 13, y: 18 },
      { row: "S", seatNumber: 17, x: 16, y: 18 },
      { row: "S", seatNumber: 18, x: 17, y: 18 },
      { row: "S", seatNumber: 19, x: 18, y: 18 },
      { row: "S", seatNumber: 20, x: 19, y: 18 },
      { row: "S", seatNumber: 21, x: 20, y: 18 },
      { row: "S", seatNumber: 22, x: 21, y: 18 },
      { row: "S", seatNumber: 23, x: 22, y: 18 },
      { row: "S", seatNumber: 24, x: 23, y: 18 },
      { row: "S", seatNumber: 25, x: 24, y: 18 },
      { row: "S", seatNumber: 26, x: 25, y: 18 },
      { row: "S", seatNumber: 27, x: 26, y: 18 },
      { row: "S", seatNumber: 28, x: 27, y: 18 },
      { row: "S", seatNumber: 29, x: 28, y: 18 },
      { row: "S", seatNumber: 30, x: 29, y: 18 },
      { row: "T", seatNumber: 1, x: 0, y: 19 },
      { row: "T", seatNumber: 2, x: 1, y: 19 },
      { row: "T", seatNumber: 3, x: 2, y: 19 },
      { row: "T", seatNumber: 4, x: 3, y: 19 },
      { row: "T", seatNumber: 5, x: 4, y: 19 },
      { row: "T", seatNumber: 6, x: 5, y: 19 },
      { row: "T", seatNumber: 7, x: 6, y: 19 },
      { row: "T", seatNumber: 8, x: 7, y: 19 },
      { row: "T", seatNumber: 9, x: 8, y: 19 },
      { row: "T", seatNumber: 10, x: 9, y: 19 },
      { row: "T", seatNumber: 11, x: 10, y: 19 },
      { row: "T", seatNumber: 12, x: 11, y: 19 },
      { row: "T", seatNumber: 13, x: 12, y: 19 },
      { row: "T", seatNumber: 14, x: 13, y: 19 },
      { row: "T", seatNumber: 17, x: 16, y: 19 },
      { row: "T", seatNumber: 18, x: 17, y: 19 },
      { row: "T", seatNumber: 19, x: 18, y: 19 },
      { row: "T", seatNumber: 20, x: 19, y: 19 },
      { row: "T", seatNumber: 21, x: 20, y: 19 },
      { row: "T", seatNumber: 22, x: 21, y: 19 },
      { row: "T", seatNumber: 23, x: 22, y: 19 },
      { row: "T", seatNumber: 24, x: 23, y: 19 },
      { row: "T", seatNumber: 25, x: 24, y: 19 },
      { row: "T", seatNumber: 26, x: 25, y: 19 },
      { row: "T", seatNumber: 27, x: 26, y: 19 },
      { row: "T", seatNumber: 28, x: 27, y: 19 },
      { row: "T", seatNumber: 29, x: 28, y: 19 },
      { row: "T", seatNumber: 30, x: 29, y: 19 },
    ],
  },
  premium: {
    rows: 23,
    columns: 28,
    seats: [
      { row: "A", seatNumber: 1, x: 0, y: 0 },
      { row: "A", seatNumber: 2, x: 1, y: 0 },
      { row: "A", seatNumber: 3, x: 2, y: 0 },
      { row: "A", seatNumber: 4, x: 3, y: 0 },
      { row: "A", seatNumber: 5, x: 4, y: 0 },
      { row: "A", seatNumber: 6, x: 5, y: 0 },
      { row: "A", seatNumber: 7, x: 6, y: 0 },
      { row: "A", seatNumber: 8, x: 7, y: 0 },
      { row: "A", seatNumber: 13, x: 12, y: 0 },
      { row: "A", seatNumber: 14, x: 13, y: 0 },
      { row: "A", seatNumber: 15, x: 14, y: 0 },
      { row: "A", seatNumber: 16, x: 15, y: 0 },
      { row: "A", seatNumber: 17, x: 16, y: 0 },
      { row: "A", seatNumber: 18, x: 17, y: 0 },
      { row: "A", seatNumber: 19, x: 18, y: 0 },
      { row: "A", seatNumber: 20, x: 19, y: 0 },
      { row: "A", seatNumber: 21, x: 20, y: 0 },
      { row: "A", seatNumber: 22, x: 21, y: 0 },
      { row: "A", seatNumber: 23, x: 22, y: 0 },
      { row: "A", seatNumber: 24, x: 23, y: 0 },
      { row: "A", seatNumber: 25, x: 24, y: 0 },
      { row: "A", seatNumber: 26, x: 25, y: 0 },
      { row: "A", seatNumber: 27, x: 26, y: 0 },
      { row: "A", seatNumber: 28, x: 27, y: 0 },
      { row: "B", seatNumber: 1, x: 0, y: 1 },
      { row: "B", seatNumber: 2, x: 1, y: 1 },
      { row: "B", seatNumber: 3, x: 2, y: 1 },
      { row: "B", seatNumber: 4, x: 3, y: 1 },
      { row: "B", seatNumber: 5, x: 4, y: 1 },
      { row: "B", seatNumber: 6, x: 5, y: 1 },
      { row: "B", seatNumber: 7, x: 6, y: 1 },
      { row: "B", seatNumber: 8, x: 7, y: 1 },
      { row: "B", seatNumber: 13, x: 12, y: 1 },
      { row: "B", seatNumber: 14, x: 13, y: 1 },
      { row: "B", seatNumber: 15, x: 14, y: 1 },
      { row: "B", seatNumber: 16, x: 15, y: 1 },
      { row: "B", seatNumber: 17, x: 16, y: 1 },
      { row: "B", seatNumber: 18, x: 17, y: 1 },
      { row: "B", seatNumber: 19, x: 18, y: 1 },
      { row: "B", seatNumber: 20, x: 19, y: 1 },
      { row: "B", seatNumber: 21, x: 20, y: 1 },
      { row: "B", seatNumber: 22, x: 21, y: 1 },
      { row: "B", seatNumber: 23, x: 22, y: 1 },
      { row: "B", seatNumber: 24, x: 23, y: 1 },
      { row: "B", seatNumber: 25, x: 24, y: 1 },
      { row: "B", seatNumber: 26, x: 25, y: 1 },
      { row: "B", seatNumber: 27, x: 26, y: 1 },
      { row: "B", seatNumber: 28, x: 27, y: 1 },
      { row: "C", seatNumber: 1, x: 0, y: 2 },
      { row: "C", seatNumber: 2, x: 1, y: 2 },
      { row: "C", seatNumber: 3, x: 2, y: 2 },
      { row: "C", seatNumber: 4, x: 3, y: 2 },
      { row: "C", seatNumber: 5, x: 4, y: 2 },
      { row: "C", seatNumber: 6, x: 5, y: 2 },
      { row: "C", seatNumber: 7, x: 6, y: 2 },
      { row: "C", seatNumber: 8, x: 7, y: 2 },
      { row: "C", seatNumber: 13, x: 12, y: 2 },
      { row: "C", seatNumber: 14, x: 13, y: 2 },
      { row: "C", seatNumber: 15, x: 14, y: 2 },
      { row: "C", seatNumber: 16, x: 15, y: 2 },
      { row: "C", seatNumber: 17, x: 16, y: 2 },
      { row: "C", seatNumber: 18, x: 17, y: 2 },
      { row: "C", seatNumber: 19, x: 18, y: 2 },
      { row: "C", seatNumber: 20, x: 19, y: 2 },
      { row: "C", seatNumber: 21, x: 20, y: 2 },
      { row: "C", seatNumber: 22, x: 21, y: 2 },
      { row: "C", seatNumber: 23, x: 22, y: 2 },
      { row: "C", seatNumber: 24, x: 23, y: 2 },
      { row: "C", seatNumber: 25, x: 24, y: 2 },
      { row: "C", seatNumber: 26, x: 25, y: 2 },
      { row: "C", seatNumber: 27, x: 26, y: 2 },
      { row: "C", seatNumber: 28, x: 27, y: 2 },
      { row: "D", seatNumber: 1, x: 0, y: 3 },
      { row: "D", seatNumber: 2, x: 1, y: 3 },
      { row: "D", seatNumber: 3, x: 2, y: 3 },
      { row: "D", seatNumber: 4, x: 3, y: 3 },
      { row: "D", seatNumber: 5, x: 4, y: 3 },
      { row: "D", seatNumber: 6, x: 5, y: 3 },
      { row: "D", seatNumber: 7, x: 6, y: 3 },
      { row: "D", seatNumber: 8, x: 7, y: 3 },
      { row: "D", seatNumber: 13, x: 12, y: 3 },
      { row: "D", seatNumber: 14, x: 13, y: 3 },
      { row: "D", seatNumber: 15, x: 14, y: 3 },
      { row: "D", seatNumber: 16, x: 15, y: 3 },
      { row: "D", seatNumber: 17, x: 16, y: 3 },
      { row: "D", seatNumber: 18, x: 17, y: 3 },
      { row: "D", seatNumber: 19, x: 18, y: 3 },
      { row: "D", seatNumber: 20, x: 19, y: 3 },
      { row: "D", seatNumber: 21, x: 20, y: 3 },
      { row: "D", seatNumber: 22, x: 21, y: 3 },
      { row: "D", seatNumber: 23, x: 22, y: 3 },
      { row: "D", seatNumber: 24, x: 23, y: 3 },
      { row: "D", seatNumber: 25, x: 24, y: 3 },
      { row: "D", seatNumber: 26, x: 25, y: 3 },
      { row: "D", seatNumber: 27, x: 26, y: 3 },
      { row: "D", seatNumber: 28, x: 27, y: 3 },
      { row: "E", seatNumber: 1, x: 0, y: 4 },
      { row: "E", seatNumber: 2, x: 1, y: 4 },
      { row: "E", seatNumber: 3, x: 2, y: 4 },
      { row: "E", seatNumber: 4, x: 3, y: 4 },
      { row: "E", seatNumber: 5, x: 4, y: 4 },
      { row: "E", seatNumber: 6, x: 5, y: 4 },
      { row: "E", seatNumber: 7, x: 6, y: 4 },
      { row: "E", seatNumber: 8, x: 7, y: 4 },
      { row: "E", seatNumber: 13, x: 12, y: 4 },
      { row: "E", seatNumber: 14, x: 13, y: 4 },
      { row: "E", seatNumber: 15, x: 14, y: 4 },
      { row: "E", seatNumber: 16, x: 15, y: 4 },
      { row: "E", seatNumber: 17, x: 16, y: 4 },
      { row: "E", seatNumber: 18, x: 17, y: 4 },
      { row: "E", seatNumber: 19, x: 18, y: 4 },
      { row: "E", seatNumber: 20, x: 19, y: 4 },
      { row: "E", seatNumber: 21, x: 20, y: 4 },
      { row: "E", seatNumber: 22, x: 21, y: 4 },
      { row: "E", seatNumber: 23, x: 22, y: 4 },
      { row: "E", seatNumber: 24, x: 23, y: 4 },
      { row: "E", seatNumber: 25, x: 24, y: 4 },
      { row: "E", seatNumber: 26, x: 25, y: 4 },
      { row: "E", seatNumber: 27, x: 26, y: 4 },
      { row: "E", seatNumber: 28, x: 27, y: 4 },
      { row: "F", seatNumber: 1, x: 0, y: 5 },
      { row: "F", seatNumber: 2, x: 1, y: 5 },
      { row: "F", seatNumber: 3, x: 2, y: 5 },
      { row: "F", seatNumber: 4, x: 3, y: 5 },
      { row: "F", seatNumber: 5, x: 4, y: 5 },
      { row: "F", seatNumber: 6, x: 5, y: 5 },
      { row: "F", seatNumber: 7, x: 6, y: 5 },
      { row: "F", seatNumber: 8, x: 7, y: 5 },
      { row: "F", seatNumber: 13, x: 12, y: 5 },
      { row: "F", seatNumber: 14, x: 13, y: 5 },
      { row: "F", seatNumber: 15, x: 14, y: 5 },
      { row: "F", seatNumber: 16, x: 15, y: 5 },
      { row: "F", seatNumber: 17, x: 16, y: 5 },
      { row: "F", seatNumber: 18, x: 17, y: 5 },
      { row: "F", seatNumber: 19, x: 18, y: 5 },
      { row: "F", seatNumber: 20, x: 19, y: 5 },
      { row: "F", seatNumber: 21, x: 20, y: 5 },
      { row: "F", seatNumber: 22, x: 21, y: 5 },
      { row: "F", seatNumber: 23, x: 22, y: 5 },
      { row: "F", seatNumber: 24, x: 23, y: 5 },
      { row: "F", seatNumber: 25, x: 24, y: 5 },
      { row: "F", seatNumber: 26, x: 25, y: 5 },
      { row: "F", seatNumber: 27, x: 26, y: 5 },
      { row: "F", seatNumber: 28, x: 27, y: 5 },
      { row: "G", seatNumber: 1, x: 0, y: 6 },
      { row: "G", seatNumber: 2, x: 1, y: 6 },
      { row: "G", seatNumber: 3, x: 2, y: 6 },
      { row: "G", seatNumber: 4, x: 3, y: 6 },
      { row: "G", seatNumber: 5, x: 4, y: 6 },
      { row: "G", seatNumber: 6, x: 5, y: 6 },
      { row: "G", seatNumber: 7, x: 6, y: 6 },
      { row: "G", seatNumber: 8, x: 7, y: 6 },
      { row: "G", seatNumber: 13, x: 12, y: 6 },
      { row: "G", seatNumber: 14, x: 13, y: 6 },
      { row: "G", seatNumber: 15, x: 14, y: 6 },
      { row: "G", seatNumber: 16, x: 15, y: 6 },
      { row: "G", seatNumber: 17, x: 16, y: 6 },
      { row: "G", seatNumber: 18, x: 17, y: 6 },
      { row: "G", seatNumber: 19, x: 18, y: 6 },
      { row: "G", seatNumber: 20, x: 19, y: 6 },
      { row: "G", seatNumber: 21, x: 20, y: 6 },
      { row: "G", seatNumber: 22, x: 21, y: 6 },
      { row: "G", seatNumber: 23, x: 22, y: 6 },
      { row: "G", seatNumber: 24, x: 23, y: 6 },
      { row: "G", seatNumber: 25, x: 24, y: 6 },
      { row: "G", seatNumber: 26, x: 25, y: 6 },
      { row: "G", seatNumber: 27, x: 26, y: 6 },
      { row: "G", seatNumber: 28, x: 27, y: 6 },
      { row: "H", seatNumber: 1, x: 0, y: 7 },
      { row: "H", seatNumber: 2, x: 1, y: 7 },
      { row: "H", seatNumber: 3, x: 2, y: 7 },
      { row: "H", seatNumber: 4, x: 3, y: 7 },
      { row: "H", seatNumber: 5, x: 4, y: 7 },
      { row: "H", seatNumber: 6, x: 5, y: 7 },
      { row: "H", seatNumber: 7, x: 6, y: 7 },
      { row: "H", seatNumber: 8, x: 7, y: 7 },
      { row: "H", seatNumber: 13, x: 12, y: 7 },
      { row: "H", seatNumber: 14, x: 13, y: 7 },
      { row: "H", seatNumber: 15, x: 14, y: 7 },
      { row: "H", seatNumber: 16, x: 15, y: 7 },
      { row: "H", seatNumber: 17, x: 16, y: 7 },
      { row: "H", seatNumber: 18, x: 17, y: 7 },
      { row: "H", seatNumber: 19, x: 18, y: 7 },
      { row: "H", seatNumber: 20, x: 19, y: 7 },
      { row: "H", seatNumber: 21, x: 20, y: 7 },
      { row: "H", seatNumber: 22, x: 21, y: 7 },
      { row: "H", seatNumber: 23, x: 22, y: 7 },
      { row: "H", seatNumber: 24, x: 23, y: 7 },
      { row: "H", seatNumber: 25, x: 24, y: 7 },
      { row: "H", seatNumber: 26, x: 25, y: 7 },
      { row: "H", seatNumber: 27, x: 26, y: 7 },
      { row: "H", seatNumber: 28, x: 27, y: 7 },
      { row: "I", seatNumber: 1, x: 0, y: 8 },
      { row: "I", seatNumber: 2, x: 1, y: 8 },
      { row: "I", seatNumber: 3, x: 2, y: 8 },
      { row: "I", seatNumber: 4, x: 3, y: 8 },
      { row: "I", seatNumber: 5, x: 4, y: 8 },
      { row: "I", seatNumber: 6, x: 5, y: 8 },
      { row: "I", seatNumber: 7, x: 6, y: 8 },
      { row: "I", seatNumber: 8, x: 7, y: 8 },
      { row: "I", seatNumber: 13, x: 12, y: 8 },
      { row: "I", seatNumber: 14, x: 13, y: 8 },
      { row: "I", seatNumber: 15, x: 14, y: 8 },
      { row: "I", seatNumber: 16, x: 15, y: 8 },
      { row: "I", seatNumber: 17, x: 16, y: 8 },
      { row: "I", seatNumber: 18, x: 17, y: 8 },
      { row: "I", seatNumber: 19, x: 18, y: 8 },
      { row: "I", seatNumber: 20, x: 19, y: 8 },
      { row: "I", seatNumber: 21, x: 20, y: 8 },
      { row: "I", seatNumber: 22, x: 21, y: 8 },
      { row: "I", seatNumber: 23, x: 22, y: 8 },
      { row: "I", seatNumber: 24, x: 23, y: 8 },
      { row: "I", seatNumber: 25, x: 24, y: 8 },
      { row: "I", seatNumber: 26, x: 25, y: 8 },
      { row: "I", seatNumber: 27, x: 26, y: 8 },
      { row: "I", seatNumber: 28, x: 27, y: 8 },
      { row: "J", seatNumber: 1, x: 0, y: 9 },
      { row: "J", seatNumber: 2, x: 1, y: 9 },
      { row: "J", seatNumber: 3, x: 2, y: 9 },
      { row: "J", seatNumber: 4, x: 3, y: 9 },
      { row: "J", seatNumber: 5, x: 4, y: 9 },
      { row: "J", seatNumber: 6, x: 5, y: 9 },
      { row: "J", seatNumber: 7, x: 6, y: 9 },
      { row: "J", seatNumber: 8, x: 7, y: 9 },
      { row: "J", seatNumber: 13, x: 12, y: 9 },
      { row: "J", seatNumber: 14, x: 13, y: 9 },
      { row: "J", seatNumber: 15, x: 14, y: 9 },
      { row: "J", seatNumber: 16, x: 15, y: 9 },
      { row: "J", seatNumber: 17, x: 16, y: 9 },
      { row: "J", seatNumber: 18, x: 17, y: 9 },
      { row: "J", seatNumber: 19, x: 18, y: 9 },
      { row: "J", seatNumber: 20, x: 19, y: 9 },
      { row: "J", seatNumber: 21, x: 20, y: 9 },
      { row: "J", seatNumber: 22, x: 21, y: 9 },
      { row: "J", seatNumber: 23, x: 22, y: 9 },
      { row: "J", seatNumber: 24, x: 23, y: 9 },
      { row: "J", seatNumber: 25, x: 24, y: 9 },
      { row: "J", seatNumber: 26, x: 25, y: 9 },
      { row: "J", seatNumber: 27, x: 26, y: 9 },
      { row: "J", seatNumber: 28, x: 27, y: 9 },
      { row: "K", seatNumber: 1, x: 0, y: 10 },
      { row: "K", seatNumber: 2, x: 1, y: 10 },
      { row: "K", seatNumber: 3, x: 2, y: 10 },
      { row: "K", seatNumber: 4, x: 3, y: 10 },
      { row: "K", seatNumber: 5, x: 4, y: 10 },
      { row: "K", seatNumber: 6, x: 5, y: 10 },
      { row: "K", seatNumber: 7, x: 6, y: 10 },
      { row: "K", seatNumber: 8, x: 7, y: 10 },
      { row: "K", seatNumber: 13, x: 12, y: 10 },
      { row: "K", seatNumber: 14, x: 13, y: 10 },
      { row: "K", seatNumber: 15, x: 14, y: 10 },
      { row: "K", seatNumber: 16, x: 15, y: 10 },
      { row: "K", seatNumber: 17, x: 16, y: 10 },
      { row: "K", seatNumber: 18, x: 17, y: 10 },
      { row: "K", seatNumber: 19, x: 18, y: 10 },
      { row: "K", seatNumber: 20, x: 19, y: 10 },
      { row: "K", seatNumber: 21, x: 20, y: 10 },
      { row: "K", seatNumber: 22, x: 21, y: 10 },
      { row: "K", seatNumber: 23, x: 22, y: 10 },
      { row: "K", seatNumber: 24, x: 23, y: 10 },
      { row: "K", seatNumber: 25, x: 24, y: 10 },
      { row: "K", seatNumber: 26, x: 25, y: 10 },
      { row: "K", seatNumber: 27, x: 26, y: 10 },
      { row: "K", seatNumber: 28, x: 27, y: 10 },
      { row: "L", seatNumber: 1, x: 0, y: 11 },
      { row: "L", seatNumber: 2, x: 1, y: 11 },
      { row: "L", seatNumber: 3, x: 2, y: 11 },
      { row: "L", seatNumber: 4, x: 3, y: 11 },
      { row: "L", seatNumber: 5, x: 4, y: 11 },
      { row: "L", seatNumber: 6, x: 5, y: 11 },
      { row: "L", seatNumber: 7, x: 6, y: 11 },
      { row: "L", seatNumber: 8, x: 7, y: 11 },
      { row: "L", seatNumber: 13, x: 12, y: 11 },
      { row: "L", seatNumber: 14, x: 13, y: 11 },
      { row: "L", seatNumber: 15, x: 14, y: 11 },
      { row: "L", seatNumber: 16, x: 15, y: 11 },
      { row: "L", seatNumber: 17, x: 16, y: 11 },
      { row: "L", seatNumber: 18, x: 17, y: 11 },
      { row: "L", seatNumber: 19, x: 18, y: 11 },
      { row: "L", seatNumber: 20, x: 19, y: 11 },
      { row: "L", seatNumber: 21, x: 20, y: 11 },
      { row: "L", seatNumber: 22, x: 21, y: 11 },
      { row: "L", seatNumber: 23, x: 22, y: 11 },
      { row: "L", seatNumber: 24, x: 23, y: 11 },
      { row: "L", seatNumber: 25, x: 24, y: 11 },
      { row: "L", seatNumber: 26, x: 25, y: 11 },
      { row: "L", seatNumber: 27, x: 26, y: 11 },
      { row: "L", seatNumber: 28, x: 27, y: 11 },
      { row: "N", seatNumber: 1, x: 0, y: 13 },
      { row: "N", seatNumber: 2, x: 1, y: 13 },
      { row: "N", seatNumber: 3, x: 2, y: 13 },
      { row: "N", seatNumber: 4, x: 3, y: 13 },
      { row: "N", seatNumber: 5, x: 4, y: 13 },
      { row: "N", seatNumber: 6, x: 5, y: 13 },
      { row: "N", seatNumber: 7, x: 6, y: 13 },
      { row: "N", seatNumber: 8, x: 7, y: 13 },
      { row: "N", seatNumber: 9, x: 8, y: 13 },
      { row: "N", seatNumber: 10, x: 9, y: 13 },
      { row: "N", seatNumber: 11, x: 10, y: 13 },
      { row: "N", seatNumber: 12, x: 11, y: 13 },
      { row: "N", seatNumber: 13, x: 12, y: 13 },
      { row: "N", seatNumber: 14, x: 13, y: 13 },
      { row: "N", seatNumber: 15, x: 14, y: 13 },
      { row: "N", seatNumber: 16, x: 15, y: 13 },
      { row: "N", seatNumber: 17, x: 16, y: 13 },
      { row: "N", seatNumber: 18, x: 17, y: 13 },
      { row: "N", seatNumber: 19, x: 18, y: 13 },
      { row: "N", seatNumber: 20, x: 19, y: 13 },
      { row: "N", seatNumber: 21, x: 20, y: 13 },
      { row: "N", seatNumber: 22, x: 21, y: 13 },
      { row: "N", seatNumber: 23, x: 22, y: 13 },
      { row: "N", seatNumber: 26, x: 25, y: 13 },
      { row: "N", seatNumber: 27, x: 26, y: 13 },
      { row: "N", seatNumber: 28, x: 27, y: 13 },
      { row: "O", seatNumber: 1, x: 0, y: 14 },
      { row: "O", seatNumber: 2, x: 1, y: 14 },
      { row: "O", seatNumber: 3, x: 2, y: 14 },
      { row: "O", seatNumber: 4, x: 3, y: 14 },
      { row: "O", seatNumber: 5, x: 4, y: 14 },
      { row: "O", seatNumber: 6, x: 5, y: 14 },
      { row: "O", seatNumber: 7, x: 6, y: 14 },
      { row: "O", seatNumber: 8, x: 7, y: 14 },
      { row: "O", seatNumber: 9, x: 8, y: 14 },
      { row: "O", seatNumber: 10, x: 9, y: 14 },
      { row: "O", seatNumber: 11, x: 10, y: 14 },
      { row: "O", seatNumber: 12, x: 11, y: 14 },
      { row: "O", seatNumber: 13, x: 12, y: 14 },
      { row: "O", seatNumber: 14, x: 13, y: 14 },
      { row: "O", seatNumber: 15, x: 14, y: 14 },
      { row: "O", seatNumber: 16, x: 15, y: 14 },
      { row: "O", seatNumber: 17, x: 16, y: 14 },
      { row: "O", seatNumber: 18, x: 17, y: 14 },
      { row: "O", seatNumber: 19, x: 18, y: 14 },
      { row: "O", seatNumber: 20, x: 19, y: 14 },
      { row: "O", seatNumber: 21, x: 20, y: 14 },
      { row: "O", seatNumber: 22, x: 21, y: 14 },
      { row: "O", seatNumber: 23, x: 22, y: 14 },
      { row: "O", seatNumber: 26, x: 25, y: 14 },
      { row: "O", seatNumber: 27, x: 26, y: 14 },
      { row: "O", seatNumber: 28, x: 27, y: 14 },
      { row: "P", seatNumber: 1, x: 0, y: 15 },
      { row: "P", seatNumber: 2, x: 1, y: 15 },
      { row: "P", seatNumber: 3, x: 2, y: 15 },
      { row: "P", seatNumber: 4, x: 3, y: 15 },
      { row: "P", seatNumber: 5, x: 4, y: 15 },
      { row: "P", seatNumber: 6, x: 5, y: 15 },
      { row: "P", seatNumber: 7, x: 6, y: 15 },
      { row: "P", seatNumber: 8, x: 7, y: 15 },
      { row: "P", seatNumber: 9, x: 8, y: 15 },
      { row: "P", seatNumber: 10, x: 9, y: 15 },
      { row: "P", seatNumber: 11, x: 10, y: 15 },
      { row: "P", seatNumber: 12, x: 11, y: 15 },
      { row: "P", seatNumber: 13, x: 12, y: 15 },
      { row: "P", seatNumber: 14, x: 13, y: 15 },
      { row: "P", seatNumber: 15, x: 14, y: 15 },
      { row: "P", seatNumber: 16, x: 15, y: 15 },
      { row: "P", seatNumber: 17, x: 16, y: 15 },
      { row: "P", seatNumber: 18, x: 17, y: 15 },
      { row: "P", seatNumber: 19, x: 18, y: 15 },
      { row: "P", seatNumber: 20, x: 19, y: 15 },
      { row: "P", seatNumber: 21, x: 20, y: 15 },
      { row: "P", seatNumber: 22, x: 21, y: 15 },
      { row: "P", seatNumber: 23, x: 22, y: 15 },
      { row: "P", seatNumber: 26, x: 25, y: 15 },
      { row: "P", seatNumber: 27, x: 26, y: 15 },
      { row: "P", seatNumber: 28, x: 27, y: 15 },
      { row: "Q", seatNumber: 1, x: 0, y: 16 },
      { row: "Q", seatNumber: 2, x: 1, y: 16 },
      { row: "Q", seatNumber: 3, x: 2, y: 16 },
      { row: "Q", seatNumber: 4, x: 3, y: 16 },
      { row: "Q", seatNumber: 5, x: 4, y: 16 },
      { row: "Q", seatNumber: 6, x: 5, y: 16 },
      { row: "Q", seatNumber: 7, x: 6, y: 16 },
      { row: "Q", seatNumber: 8, x: 7, y: 16 },
      { row: "Q", seatNumber: 9, x: 8, y: 16 },
      { row: "Q", seatNumber: 10, x: 9, y: 16 },
      { row: "Q", seatNumber: 11, x: 10, y: 16 },
      { row: "Q", seatNumber: 12, x: 11, y: 16 },
      { row: "Q", seatNumber: 13, x: 12, y: 16 },
      { row: "Q", seatNumber: 14, x: 13, y: 16 },
      { row: "Q", seatNumber: 15, x: 14, y: 16 },
      { row: "Q", seatNumber: 16, x: 15, y: 16 },
      { row: "Q", seatNumber: 17, x: 16, y: 16 },
      { row: "Q", seatNumber: 18, x: 17, y: 16 },
      { row: "Q", seatNumber: 19, x: 18, y: 16 },
      { row: "Q", seatNumber: 20, x: 19, y: 16 },
      { row: "Q", seatNumber: 21, x: 20, y: 16 },
      { row: "Q", seatNumber: 22, x: 21, y: 16 },
      { row: "Q", seatNumber: 23, x: 22, y: 16 },
      { row: "Q", seatNumber: 26, x: 25, y: 16 },
      { row: "Q", seatNumber: 27, x: 26, y: 16 },
      { row: "Q", seatNumber: 28, x: 27, y: 16 },
      { row: "R", seatNumber: 1, x: 0, y: 17 },
      { row: "R", seatNumber: 2, x: 1, y: 17 },
      { row: "R", seatNumber: 3, x: 2, y: 17 },
      { row: "R", seatNumber: 4, x: 3, y: 17 },
      { row: "R", seatNumber: 5, x: 4, y: 17 },
      { row: "R", seatNumber: 6, x: 5, y: 17 },
      { row: "R", seatNumber: 7, x: 6, y: 17 },
      { row: "R", seatNumber: 8, x: 7, y: 17 },
      { row: "R", seatNumber: 9, x: 8, y: 17 },
      { row: "R", seatNumber: 10, x: 9, y: 17 },
      { row: "R", seatNumber: 11, x: 10, y: 17 },
      { row: "R", seatNumber: 12, x: 11, y: 17 },
      { row: "R", seatNumber: 13, x: 12, y: 17 },
      { row: "R", seatNumber: 14, x: 13, y: 17 },
      { row: "R", seatNumber: 15, x: 14, y: 17 },
      { row: "R", seatNumber: 16, x: 15, y: 17 },
      { row: "R", seatNumber: 17, x: 16, y: 17 },
      { row: "R", seatNumber: 18, x: 17, y: 17 },
      { row: "R", seatNumber: 19, x: 18, y: 17 },
      { row: "R", seatNumber: 20, x: 19, y: 17 },
      { row: "R", seatNumber: 21, x: 20, y: 17 },
      { row: "R", seatNumber: 22, x: 21, y: 17 },
      { row: "R", seatNumber: 23, x: 22, y: 17 },
      { row: "R", seatNumber: 26, x: 25, y: 17 },
      { row: "R", seatNumber: 27, x: 26, y: 17 },
      { row: "R", seatNumber: 28, x: 27, y: 17 },
      { row: "S", seatNumber: 1, x: 0, y: 18 },
      { row: "S", seatNumber: 2, x: 1, y: 18 },
      { row: "S", seatNumber: 3, x: 2, y: 18 },
      { row: "S", seatNumber: 4, x: 3, y: 18 },
      { row: "S", seatNumber: 5, x: 4, y: 18 },
      { row: "S", seatNumber: 6, x: 5, y: 18 },
      { row: "S", seatNumber: 7, x: 6, y: 18 },
      { row: "S", seatNumber: 8, x: 7, y: 18 },
      { row: "S", seatNumber: 9, x: 8, y: 18 },
      { row: "S", seatNumber: 10, x: 9, y: 18 },
      { row: "S", seatNumber: 11, x: 10, y: 18 },
      { row: "S", seatNumber: 12, x: 11, y: 18 },
      { row: "S", seatNumber: 13, x: 12, y: 18 },
      { row: "S", seatNumber: 14, x: 13, y: 18 },
      { row: "S", seatNumber: 15, x: 14, y: 18 },
      { row: "S", seatNumber: 16, x: 15, y: 18 },
      { row: "S", seatNumber: 17, x: 16, y: 18 },
      { row: "S", seatNumber: 18, x: 17, y: 18 },
      { row: "S", seatNumber: 19, x: 18, y: 18 },
      { row: "S", seatNumber: 20, x: 19, y: 18 },
      { row: "S", seatNumber: 21, x: 20, y: 18 },
      { row: "S", seatNumber: 22, x: 21, y: 18 },
      { row: "S", seatNumber: 23, x: 22, y: 18 },
      { row: "S", seatNumber: 26, x: 25, y: 18 },
      { row: "S", seatNumber: 27, x: 26, y: 18 },
      { row: "S", seatNumber: 28, x: 27, y: 18 },
      { row: "T", seatNumber: 1, x: 0, y: 19 },
      { row: "T", seatNumber: 2, x: 1, y: 19 },
      { row: "T", seatNumber: 3, x: 2, y: 19 },
      { row: "T", seatNumber: 4, x: 3, y: 19 },
      { row: "T", seatNumber: 5, x: 4, y: 19 },
      { row: "T", seatNumber: 6, x: 5, y: 19 },
      { row: "T", seatNumber: 7, x: 6, y: 19 },
      { row: "T", seatNumber: 8, x: 7, y: 19 },
      { row: "T", seatNumber: 9, x: 8, y: 19 },
      { row: "T", seatNumber: 10, x: 9, y: 19 },
      { row: "T", seatNumber: 11, x: 10, y: 19 },
      { row: "T", seatNumber: 12, x: 11, y: 19 },
      { row: "T", seatNumber: 13, x: 12, y: 19 },
      { row: "T", seatNumber: 14, x: 13, y: 19 },
      { row: "T", seatNumber: 15, x: 14, y: 19 },
      { row: "T", seatNumber: 16, x: 15, y: 19 },
      { row: "T", seatNumber: 17, x: 16, y: 19 },
      { row: "T", seatNumber: 18, x: 17, y: 19 },
      { row: "T", seatNumber: 19, x: 18, y: 19 },
      { row: "T", seatNumber: 20, x: 19, y: 19 },
      { row: "T", seatNumber: 21, x: 20, y: 19 },
      { row: "T", seatNumber: 22, x: 21, y: 19 },
      { row: "T", seatNumber: 23, x: 22, y: 19 },
      { row: "T", seatNumber: 26, x: 25, y: 19 },
      { row: "T", seatNumber: 27, x: 26, y: 19 },
      { row: "T", seatNumber: 28, x: 27, y: 19 },
      { row: "U", seatNumber: 1, x: 0, y: 20 },
      { row: "U", seatNumber: 2, x: 1, y: 20 },
      { row: "U", seatNumber: 3, x: 2, y: 20 },
      { row: "U", seatNumber: 4, x: 3, y: 20 },
      { row: "U", seatNumber: 5, x: 4, y: 20 },
      { row: "U", seatNumber: 6, x: 5, y: 20 },
      { row: "U", seatNumber: 7, x: 6, y: 20 },
      { row: "U", seatNumber: 8, x: 7, y: 20 },
      { row: "U", seatNumber: 9, x: 8, y: 20 },
      { row: "U", seatNumber: 10, x: 9, y: 20 },
      { row: "U", seatNumber: 11, x: 10, y: 20 },
      { row: "U", seatNumber: 12, x: 11, y: 20 },
      { row: "U", seatNumber: 13, x: 12, y: 20 },
      { row: "U", seatNumber: 14, x: 13, y: 20 },
      { row: "U", seatNumber: 15, x: 14, y: 20 },
      { row: "U", seatNumber: 16, x: 15, y: 20 },
      { row: "U", seatNumber: 17, x: 16, y: 20 },
      { row: "U", seatNumber: 18, x: 17, y: 20 },
      { row: "U", seatNumber: 19, x: 18, y: 20 },
      { row: "U", seatNumber: 20, x: 19, y: 20 },
      { row: "U", seatNumber: 21, x: 20, y: 20 },
      { row: "U", seatNumber: 22, x: 21, y: 20 },
      { row: "U", seatNumber: 23, x: 22, y: 20 },
      { row: "U", seatNumber: 26, x: 25, y: 20 },
      { row: "U", seatNumber: 27, x: 26, y: 20 },
      { row: "U", seatNumber: 28, x: 27, y: 20 },
      { row: "V", seatNumber: 1, x: 0, y: 21 },
      { row: "V", seatNumber: 2, x: 1, y: 21 },
      { row: "V", seatNumber: 3, x: 2, y: 21 },
      { row: "V", seatNumber: 4, x: 3, y: 21 },
      { row: "V", seatNumber: 5, x: 4, y: 21 },
      { row: "V", seatNumber: 6, x: 5, y: 21 },
      { row: "V", seatNumber: 7, x: 6, y: 21 },
      { row: "V", seatNumber: 8, x: 7, y: 21 },
      { row: "V", seatNumber: 9, x: 8, y: 21 },
      { row: "V", seatNumber: 10, x: 9, y: 21 },
      { row: "V", seatNumber: 11, x: 10, y: 21 },
      { row: "V", seatNumber: 12, x: 11, y: 21 },
      { row: "V", seatNumber: 13, x: 12, y: 21 },
      { row: "V", seatNumber: 14, x: 13, y: 21 },
      { row: "V", seatNumber: 15, x: 14, y: 21 },
      { row: "V", seatNumber: 16, x: 15, y: 21 },
      { row: "V", seatNumber: 17, x: 16, y: 21 },
      { row: "V", seatNumber: 18, x: 17, y: 21 },
      { row: "V", seatNumber: 19, x: 18, y: 21 },
      { row: "V", seatNumber: 20, x: 19, y: 21 },
      { row: "V", seatNumber: 21, x: 20, y: 21 },
      { row: "V", seatNumber: 22, x: 21, y: 21 },
      { row: "V", seatNumber: 23, x: 22, y: 21 },
      { row: "V", seatNumber: 26, x: 25, y: 21 },
      { row: "V", seatNumber: 27, x: 26, y: 21 },
      { row: "V", seatNumber: 28, x: 27, y: 21 },
      { row: "W", seatNumber: 1, x: 0, y: 22 },
      { row: "W", seatNumber: 2, x: 1, y: 22 },
      { row: "W", seatNumber: 3, x: 2, y: 22 },
      { row: "W", seatNumber: 4, x: 3, y: 22 },
      { row: "W", seatNumber: 5, x: 4, y: 22 },
      { row: "W", seatNumber: 6, x: 5, y: 22 },
      { row: "W", seatNumber: 7, x: 6, y: 22 },
      { row: "W", seatNumber: 8, x: 7, y: 22 },
      { row: "W", seatNumber: 9, x: 8, y: 22 },
      { row: "W", seatNumber: 10, x: 9, y: 22 },
      { row: "W", seatNumber: 11, x: 10, y: 22 },
      { row: "W", seatNumber: 12, x: 11, y: 22 },
      { row: "W", seatNumber: 13, x: 12, y: 22 },
      { row: "W", seatNumber: 14, x: 13, y: 22 },
      { row: "W", seatNumber: 15, x: 14, y: 22 },
      { row: "W", seatNumber: 16, x: 15, y: 22 },
      { row: "W", seatNumber: 17, x: 16, y: 22 },
      { row: "W", seatNumber: 18, x: 17, y: 22 },
      { row: "W", seatNumber: 19, x: 18, y: 22 },
      { row: "W", seatNumber: 20, x: 19, y: 22 },
      { row: "W", seatNumber: 21, x: 20, y: 22 },
      { row: "W", seatNumber: 22, x: 21, y: 22 },
      { row: "W", seatNumber: 23, x: 22, y: 22 },
      { row: "W", seatNumber: 26, x: 25, y: 22 },
      { row: "W", seatNumber: 27, x: 26, y: 22 },
      { row: "W", seatNumber: 28, x: 27, y: 22 },
    ],
  },
  vip: {
    rows: 23,
    columns: 16,
    seats: [
      { row: "A", seatNumber: 1, x: 0, y: 0 },
      { row: "A", seatNumber: 2, x: 1, y: 0 },
      { row: "A", seatNumber: 3, x: 2, y: 0 },
      { row: "A", seatNumber: 4, x: 3, y: 0 },
      { row: "A", seatNumber: 5, x: 4, y: 0 },
      { row: "A", seatNumber: 6, x: 5, y: 0 },
      { row: "A", seatNumber: 7, x: 6, y: 0 },
      { row: "A", seatNumber: 9, x: 8, y: 0 },
      { row: "A", seatNumber: 10, x: 9, y: 0 },
      { row: "A", seatNumber: 11, x: 10, y: 0 },
      { row: "A", seatNumber: 12, x: 11, y: 0 },
      { row: "B", seatNumber: 13, x: 12, y: 1 },
      { row: "B", seatNumber: 14, x: 13, y: 1 },
      { row: "B", seatNumber: 15, x: 14, y: 1 },
      { row: "B", seatNumber: 16, x: 15, y: 1 },
      { row: "C", seatNumber: 1, x: 0, y: 2 },
      { row: "C", seatNumber: 2, x: 1, y: 2 },
      { row: "C", seatNumber: 3, x: 2, y: 2 },
      { row: "C", seatNumber: 4, x: 3, y: 2 },
      { row: "C", seatNumber: 5, x: 4, y: 2 },
      { row: "C", seatNumber: 6, x: 5, y: 2 },
      { row: "C", seatNumber: 7, x: 6, y: 2 },
      { row: "C", seatNumber: 10, x: 9, y: 2 },
      { row: "C", seatNumber: 11, x: 10, y: 2 },
      { row: "C", seatNumber: 12, x: 11, y: 2 },
      { row: "C", seatNumber: 13, x: 12, y: 2 },
      { row: "C", seatNumber: 14, x: 13, y: 2 },
      { row: "C", seatNumber: 15, x: 14, y: 2 },
      { row: "C", seatNumber: 16, x: 15, y: 2 },
      { row: "D", seatNumber: 1, x: 0, y: 3 },
      { row: "D", seatNumber: 2, x: 1, y: 3 },
      { row: "D", seatNumber: 7, x: 6, y: 3 },
      { row: "D", seatNumber: 10, x: 9, y: 3 },
      { row: "D", seatNumber: 11, x: 10, y: 3 },
      { row: "D", seatNumber: 12, x: 11, y: 3 },
      { row: "D", seatNumber: 13, x: 12, y: 3 },
      { row: "D", seatNumber: 14, x: 13, y: 3 },
      { row: "D", seatNumber: 15, x: 14, y: 3 },
      { row: "D", seatNumber: 16, x: 15, y: 3 },
      { row: "E", seatNumber: 1, x: 0, y: 4 },
      { row: "E", seatNumber: 2, x: 1, y: 4 },
      { row: "E", seatNumber: 3, x: 2, y: 4 },
      { row: "E", seatNumber: 4, x: 3, y: 4 },
      { row: "E", seatNumber: 5, x: 4, y: 4 },

      { row: "F", seatNumber: 5, x: 4, y: 5 },
      { row: "F", seatNumber: 6, x: 5, y: 5 },
      { row: "F", seatNumber: 7, x: 6, y: 5 },
      { row: "F", seatNumber: 10, x: 9, y: 5 },
      { row: "F", seatNumber: 11, x: 10, y: 5 },
      { row: "F", seatNumber: 12, x: 11, y: 5 },
      { row: "F", seatNumber: 13, x: 12, y: 5 },
      { row: "F", seatNumber: 14, x: 13, y: 5 },
      { row: "F", seatNumber: 15, x: 14, y: 5 },
      { row: "F", seatNumber: 16, x: 15, y: 5 },
      { row: "G", seatNumber: 1, x: 0, y: 6 },
      { row: "G", seatNumber: 2, x: 1, y: 6 },

      { row: "G", seatNumber: 14, x: 13, y: 6 },
      { row: "G", seatNumber: 15, x: 14, y: 6 },
      { row: "G", seatNumber: 16, x: 15, y: 6 },
      { row: "H", seatNumber: 1, x: 0, y: 7 },
      { row: "H", seatNumber: 2, x: 1, y: 7 },
      { row: "H", seatNumber: 3, x: 2, y: 7 },
      { row: "H", seatNumber: 4, x: 3, y: 7 },
      { row: "H", seatNumber: 5, x: 4, y: 7 },
      { row: "H", seatNumber: 6, x: 5, y: 7 },
      { row: "H", seatNumber: 7, x: 6, y: 7 },
      { row: "H", seatNumber: 10, x: 9, y: 7 },
      { row: "H", seatNumber: 11, x: 10, y: 7 },
      { row: "H", seatNumber: 12, x: 11, y: 7 },
      { row: "H", seatNumber: 13, x: 12, y: 7 },
      { row: "H", seatNumber: 14, x: 13, y: 7 },
      { row: "H", seatNumber: 15, x: 14, y: 7 },
      { row: "H", seatNumber: 16, x: 15, y: 7 },
      { row: "I", seatNumber: 1, x: 0, y: 8 },
      { row: "I", seatNumber: 2, x: 1, y: 8 },
      { row: "I", seatNumber: 3, x: 2, y: 8 },
      { row: "I", seatNumber: 4, x: 3, y: 8 },
      { row: "I", seatNumber: 5, x: 4, y: 8 },
      { row: "I", seatNumber: 6, x: 5, y: 8 },
      { row: "I", seatNumber: 7, x: 6, y: 8 },
      { row: "I", seatNumber: 10, x: 9, y: 8 },
      { row: "I", seatNumber: 11, x: 10, y: 8 },
      { row: "I", seatNumber: 12, x: 11, y: 8 },
      { row: "I", seatNumber: 13, x: 12, y: 8 },
      { row: "I", seatNumber: 14, x: 13, y: 8 },
      { row: "I", seatNumber: 15, x: 14, y: 8 },
      { row: "I", seatNumber: 16, x: 15, y: 8 },
      { row: "J", seatNumber: 1, x: 0, y: 9 },
      { row: "J", seatNumber: 2, x: 1, y: 9 },
      { row: "J", seatNumber: 3, x: 2, y: 9 },
      { row: "J", seatNumber: 4, x: 3, y: 9 },
      { row: "J", seatNumber: 5, x: 4, y: 9 },
      { row: "J", seatNumber: 6, x: 5, y: 9 },
      { row: "J", seatNumber: 7, x: 6, y: 9 },
      { row: "J", seatNumber: 10, x: 9, y: 9 },
      { row: "J", seatNumber: 11, x: 10, y: 9 },
      { row: "J", seatNumber: 12, x: 11, y: 9 },
      { row: "J", seatNumber: 13, x: 12, y: 9 },
      { row: "J", seatNumber: 14, x: 13, y: 9 },
      { row: "J", seatNumber: 15, x: 14, y: 9 },
      { row: "J", seatNumber: 16, x: 15, y: 9 },
      { row: "L", seatNumber: 1, x: 0, y: 11 },
      { row: "L", seatNumber: 2, x: 1, y: 11 },
      { row: "L", seatNumber: 3, x: 2, y: 11 },
      { row: "L", seatNumber: 4, x: 3, y: 11 },
      { row: "L", seatNumber: 5, x: 4, y: 11 },
      { row: "L", seatNumber: 6, x: 5, y: 11 },
      { row: "L", seatNumber: 7, x: 6, y: 11 },
      { row: "L", seatNumber: 10, x: 9, y: 11 },
      { row: "L", seatNumber: 11, x: 10, y: 11 },
      { row: "L", seatNumber: 12, x: 11, y: 11 },
      { row: "L", seatNumber: 13, x: 12, y: 11 },
      { row: "L", seatNumber: 14, x: 13, y: 11 },
      { row: "L", seatNumber: 15, x: 14, y: 11 },
      { row: "L", seatNumber: 16, x: 15, y: 11 },
      { row: "M", seatNumber: 1, x: 0, y: 12 },
      { row: "M", seatNumber: 2, x: 1, y: 12 },
      { row: "M", seatNumber: 3, x: 2, y: 12 },
      { row: "M", seatNumber: 4, x: 3, y: 12 },
      { row: "M", seatNumber: 5, x: 4, y: 12 },
      { row: "M", seatNumber: 6, x: 5, y: 12 },
      { row: "M", seatNumber: 7, x: 6, y: 12 },
      { row: "M", seatNumber: 10, x: 9, y: 12 },
      { row: "M", seatNumber: 11, x: 10, y: 12 },
      { row: "M", seatNumber: 12, x: 11, y: 12 },
      { row: "M", seatNumber: 13, x: 12, y: 12 },
      { row: "M", seatNumber: 14, x: 13, y: 12 },
      { row: "M", seatNumber: 15, x: 14, y: 12 },
      { row: "M", seatNumber: 16, x: 15, y: 12 },
      { row: "N", seatNumber: 1, x: 0, y: 13 },
      { row: "N", seatNumber: 2, x: 1, y: 13 },
      { row: "N", seatNumber: 3, x: 2, y: 13 },
      { row: "N", seatNumber: 4, x: 3, y: 13 },
      { row: "N", seatNumber: 5, x: 4, y: 13 },
      { row: "N", seatNumber: 6, x: 5, y: 13 },
      { row: "N", seatNumber: 7, x: 6, y: 13 },
      { row: "N", seatNumber: 10, x: 9, y: 13 },
      { row: "N", seatNumber: 11, x: 10, y: 13 },
      { row: "N", seatNumber: 12, x: 11, y: 13 },
      { row: "N", seatNumber: 13, x: 12, y: 13 },
      { row: "N", seatNumber: 14, x: 13, y: 13 },
      { row: "N", seatNumber: 15, x: 14, y: 13 },
      { row: "N", seatNumber: 16, x: 15, y: 13 },
      { row: "O", seatNumber: 1, x: 0, y: 14 },
      { row: "O", seatNumber: 2, x: 1, y: 14 },
      { row: "O", seatNumber: 3, x: 2, y: 14 },
      { row: "O", seatNumber: 4, x: 3, y: 14 },
      { row: "O", seatNumber: 5, x: 4, y: 14 },
      { row: "O", seatNumber: 6, x: 5, y: 14 },
      { row: "O", seatNumber: 7, x: 6, y: 14 },
      { row: "O", seatNumber: 10, x: 9, y: 14 },
      { row: "O", seatNumber: 11, x: 10, y: 14 },
      { row: "O", seatNumber: 12, x: 11, y: 14 },
      { row: "O", seatNumber: 13, x: 12, y: 14 },
      { row: "O", seatNumber: 14, x: 13, y: 14 },
      { row: "O", seatNumber: 15, x: 14, y: 14 },
      { row: "O", seatNumber: 16, x: 15, y: 14 },
      { row: "P", seatNumber: 1, x: 0, y: 15 },
      { row: "P", seatNumber: 2, x: 1, y: 15 },
      { row: "P", seatNumber: 3, x: 2, y: 15 },
      { row: "P", seatNumber: 4, x: 3, y: 15 },
      { row: "P", seatNumber: 5, x: 4, y: 15 },
      { row: "P", seatNumber: 6, x: 5, y: 15 },
      { row: "P", seatNumber: 7, x: 6, y: 15 },
      { row: "P", seatNumber: 10, x: 9, y: 15 },
      { row: "P", seatNumber: 11, x: 10, y: 15 },
      { row: "P", seatNumber: 12, x: 11, y: 15 },
      { row: "P", seatNumber: 13, x: 12, y: 15 },
      { row: "P", seatNumber: 14, x: 13, y: 15 },
      { row: "P", seatNumber: 15, x: 14, y: 15 },
      { row: "P", seatNumber: 16, x: 15, y: 15 },
      { row: "Q", seatNumber: 1, x: 0, y: 16 },
      { row: "Q", seatNumber: 2, x: 1, y: 16 },
      { row: "Q", seatNumber: 3, x: 2, y: 16 },
      { row: "Q", seatNumber: 4, x: 3, y: 16 },
      { row: "Q", seatNumber: 5, x: 4, y: 16 },
      { row: "Q", seatNumber: 6, x: 5, y: 16 },
      { row: "Q", seatNumber: 7, x: 6, y: 16 },
      { row: "Q", seatNumber: 10, x: 9, y: 16 },
      { row: "Q", seatNumber: 11, x: 10, y: 16 },
      { row: "Q", seatNumber: 12, x: 11, y: 16 },
      { row: "Q", seatNumber: 13, x: 12, y: 16 },
      { row: "Q", seatNumber: 14, x: 13, y: 16 },
      { row: "Q", seatNumber: 15, x: 14, y: 16 },
      { row: "Q", seatNumber: 16, x: 15, y: 16 },
      { row: "R", seatNumber: 1, x: 0, y: 17 },
      { row: "R", seatNumber: 2, x: 1, y: 17 },
      { row: "R", seatNumber: 3, x: 2, y: 17 },
      { row: "R", seatNumber: 4, x: 3, y: 17 },
      { row: "R", seatNumber: 5, x: 4, y: 17 },
      { row: "R", seatNumber: 6, x: 5, y: 17 },
      { row: "R", seatNumber: 7, x: 6, y: 17 },
      { row: "R", seatNumber: 10, x: 9, y: 17 },
      { row: "R", seatNumber: 11, x: 10, y: 17 },
      { row: "R", seatNumber: 12, x: 11, y: 17 },
      { row: "R", seatNumber: 13, x: 12, y: 17 },
      { row: "R", seatNumber: 14, x: 13, y: 17 },
      { row: "R", seatNumber: 15, x: 14, y: 17 },
      { row: "R", seatNumber: 16, x: 15, y: 17 },
      { row: "T", seatNumber: 1, x: 0, y: 19 },
      { row: "T", seatNumber: 2, x: 1, y: 19 },
      { row: "T", seatNumber: 3, x: 2, y: 19 },
      { row: "T", seatNumber: 4, x: 3, y: 19 },
      { row: "T", seatNumber: 5, x: 4, y: 19 },
      { row: "T", seatNumber: 6, x: 5, y: 19 },
      { row: "T", seatNumber: 7, x: 6, y: 19 },
      { row: "T", seatNumber: 10, x: 9, y: 19 },
      { row: "T", seatNumber: 11, x: 10, y: 19 },
      { row: "T", seatNumber: 12, x: 11, y: 19 },
      { row: "T", seatNumber: 13, x: 12, y: 19 },
      { row: "T", seatNumber: 14, x: 13, y: 19 },
      { row: "T", seatNumber: 15, x: 14, y: 19 },
      { row: "T", seatNumber: 16, x: 15, y: 19 },
      { row: "U", seatNumber: 1, x: 0, y: 20 },
      { row: "U", seatNumber: 2, x: 1, y: 20 },
      { row: "U", seatNumber: 3, x: 2, y: 20 },
      { row: "U", seatNumber: 4, x: 3, y: 20 },
      { row: "U", seatNumber: 5, x: 4, y: 20 },
      { row: "U", seatNumber: 6, x: 5, y: 20 },
      { row: "U", seatNumber: 7, x: 6, y: 20 },
      { row: "U", seatNumber: 10, x: 9, y: 20 },
      { row: "U", seatNumber: 11, x: 10, y: 20 },
      { row: "U", seatNumber: 12, x: 11, y: 20 },
      { row: "V", seatNumber: 12, x: 11, y: 21 },
      { row: "V", seatNumber: 13, x: 12, y: 21 },
      { row: "V", seatNumber: 14, x: 13, y: 21 },
      { row: "V", seatNumber: 15, x: 14, y: 21 },
      { row: "V", seatNumber: 16, x: 15, y: 21 },
      { row: "W", seatNumber: 1, x: 0, y: 22 },
      { row: "W", seatNumber: 2, x: 1, y: 22 },
      { row: "W", seatNumber: 3, x: 2, y: 22 },
      { row: "W", seatNumber: 4, x: 3, y: 22 },
      { row: "W", seatNumber: 5, x: 4, y: 22 },
      { row: "W", seatNumber: 6, x: 5, y: 22 },
      { row: "W", seatNumber: 7, x: 6, y: 22 },
      { row: "W", seatNumber: 8, x: 7, y: 22 },
      { row: "W", seatNumber: 9, x: 8, y: 22 },
      { row: "W", seatNumber: 10, x: 9, y: 22 },
      { row: "W", seatNumber: 11, x: 10, y: 22 },
      { row: "W", seatNumber: 12, x: 11, y: 22 },
      { row: "W", seatNumber: 13, x: 12, y: 22 },
      { row: "W", seatNumber: 14, x: 13, y: 22 },
      { row: "W", seatNumber: 15, x: 14, y: 22 },
      { row: "W", seatNumber: 16, x: 15, y: 22 },
    ],
  },
};

export interface BusLayout {
  rows: number;
  columns: number;
  seats: BusSeat[];
}

export interface BusSeat {
  row: string;
  seatNumber: number;
  x: number;
  y: number;
  type: string;
  isActive: boolean;
  isAccessible: boolean;
  bookedGender?: 'male' | 'female';
}

export const busLayout: BusLayout = {
  "rows": 11,
  "columns": 5,
  "seats": [
    {
      "row": "A",
      "seatNumber": 1,
      "x": 0,
      "y": 0,
      "type": "seat",
      "isActive": false,
      "isAccessible": false,
      "bookedGender": "female"
    },
    {
      "row": "B",
      "seatNumber": 1,
      "x": 0,
      "y": 1,
      "type": "seat",
      "isActive": false,
      "isAccessible": false,
      "bookedGender": "female"
    },
    {
      "row": "A",
      "seatNumber": 3,
      "x": 3,
      "y": 0,
      "type": "seat",
      "isActive": false,
      "isAccessible": false,
      "bookedGender": "male"
    },
    {
      "row": "C",
      "seatNumber": 1,
      "x": 0,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 1,
      "x": 0,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 1,
      "x": 0,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 2,
      "x": 1,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 2,
      "x": 1,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 2,
      "x": 1,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 2,
      "x": 1,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 2,
      "x": 1,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 3,
      "x": 3,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 3,
      "x": 3,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 3,
      "x": 3,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 3,
      "x": 3,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 4,
      "x": 4,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 4,
      "x": 4,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 4,
      "x": 4,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 4,
      "x": 4,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 4,
      "x": 4,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 1,
      "x": 0,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 2,
      "x": 1,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 3,
      "x": 3,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 4,
      "x": 4,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 1,
      "x": 0,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 2,
      "x": 1,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 3,
      "x": 3,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 4,
      "x": 4,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 1,
      "x": 0,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 2,
      "x": 1,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 3,
      "x": 3,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 4,
      "x": 4,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 1,
      "x": 0,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 2,
      "x": 1,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 3,
      "x": 3,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 4,
      "x": 4,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 1,
      "x": 0,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 2,
      "x": 1,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 3,
      "x": 2,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 4,
      "x": 3,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 5,
      "x": 4,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    }
  ]
}


export const planeLayout: BusLayout = {
  "rows": 11,
  "columns": 5,
  "seats": [
    {
      "row": "A",
      "seatNumber": 1,
      "x": 0,
      "y": 0,
      "type": "seat",
      "isActive": false,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 1,
      "x": 0,
      "y": 1,
      "type": "seat",
      "isActive": false,
      "isAccessible": false,
    },
    {
      "row": "A",
      "seatNumber": 3,
      "x": 3,
      "y": 0,
      "type": "seat",
      "isActive": false,
      "isAccessible": false,
    },
    {
      "row": "C",
      "seatNumber": 1,
      "x": 0,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 1,
      "x": 0,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 1,
      "x": 0,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 2,
      "x": 1,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 2,
      "x": 1,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 2,
      "x": 1,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 2,
      "x": 1,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 2,
      "x": 1,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 3,
      "x": 3,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 3,
      "x": 3,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 3,
      "x": 3,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 3,
      "x": 3,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 4,
      "x": 4,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 4,
      "x": 4,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 4,
      "x": 4,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 4,
      "x": 4,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 4,
      "x": 4,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 1,
      "x": 0,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 2,
      "x": 1,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 3,
      "x": 3,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 4,
      "x": 4,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 1,
      "x": 0,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 2,
      "x": 1,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 3,
      "x": 3,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 4,
      "x": 4,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 1,
      "x": 0,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 2,
      "x": 1,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 3,
      "x": 3,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 4,
      "x": 4,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 1,
      "x": 0,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 2,
      "x": 1,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 3,
      "x": 3,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 4,
      "x": 4,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 1,
      "x": 0,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 2,
      "x": 1,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 3,
      "x": 2,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 4,
      "x": 3,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 5,
      "x": 4,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    }
  ]
}
export const trainCouchLayout: BusLayout = {
  "rows": 15,
  "columns": 7,
  "seats": [
    {
      "row": "A",
      "seatNumber": 1,
      "x": 0,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 3,
      "x": 2,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 1,
      "x": 0,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 3,
      "x": 2,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 3,
      "x": 2,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 1,
      "x": 0,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 1,
      "x": 0,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 1,
      "x": 0,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 2,
      "x": 1,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 2,
      "x": 1,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 2,
      "x": 1,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 2,
      "x": 1,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 2,
      "x": 1,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 4,
      "x": 4,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 4,
      "x": 4,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 4,
      "x": 4,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 4,
      "x": 4,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 4,
      "x": 4,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 1,
      "x": 0,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 2,
      "x": 1,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 4,
      "x": 4,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 1,
      "x": 0,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 2,
      "x": 1,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 4,
      "x": 4,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 1,
      "x": 0,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 2,
      "x": 1,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 4,
      "x": 4,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 1,
      "x": 0,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 2,
      "x": 1,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 4,
      "x": 4,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 1,
      "x": 0,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 2,
      "x": 1,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 3,
      "x": 2,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 4,
      "x": 4,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 3,
      "x": 2,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 3,
      "x": 2,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 3,
      "x": 2,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 5,
      "x": 5,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "A",
      "seatNumber": 6,
      "x": 6,
      "y": 0,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 6,
      "x": 6,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "B",
      "seatNumber": 5,
      "x": 5,
      "y": 1,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 5,
      "x": 5,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 5,
      "x": 5,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 5,
      "x": 5,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 5,
      "x": 5,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 5,
      "x": 5,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 5,
      "x": 5,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 5,
      "x": 5,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 5,
      "x": 5,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "J",
      "seatNumber": 6,
      "x": 6,
      "y": 9,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 6,
      "x": 6,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 6,
      "x": 6,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 6,
      "x": 6,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "F",
      "seatNumber": 6,
      "x": 6,
      "y": 5,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "E",
      "seatNumber": 6,
      "x": 6,
      "y": 4,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "D",
      "seatNumber": 6,
      "x": 6,
      "y": 3,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "C",
      "seatNumber": 6,
      "x": 6,
      "y": 2,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 1,
      "x": 0,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 2,
      "x": 1,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 3,
      "x": 2,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 4,
      "x": 4,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 6,
      "x": 6,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 6,
      "x": 6,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 6,
      "x": 6,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 5,
      "x": 5,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 3,
      "x": 2,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 2,
      "x": 1,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 1,
      "x": 0,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 1,
      "x": 0,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 1,
      "x": 0,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 2,
      "x": 1,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 3,
      "x": 2,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 4,
      "x": 4,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "L",
      "seatNumber": 5,
      "x": 5,
      "y": 11,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "K",
      "seatNumber": 5,
      "x": 5,
      "y": 10,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 5,
      "x": 5,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 4,
      "x": 4,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 3,
      "x": 2,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "M",
      "seatNumber": 2,
      "x": 1,
      "y": 12,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 4,
      "x": 4,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 1,
      "x": 0,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 2,
      "x": 1,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 3,
      "x": 2,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 4,
      "x": 4,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 5,
      "x": 5,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "O",
      "seatNumber": 6,
      "x": 6,
      "y": 14,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "N",
      "seatNumber": 6,
      "x": 6,
      "y": 13,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "G",
      "seatNumber": 3,
      "x": 2,
      "y": 6,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "H",
      "seatNumber": 3,
      "x": 2,
      "y": 7,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    },
    {
      "row": "I",
      "seatNumber": 3,
      "x": 2,
      "y": 8,
      "type": "seat",
      "isActive": true,
      "isAccessible": false
    }
  ]
}
