import { t, type UnwrapSchema } from 'elysia'

export const CinemaModel = {
	theaterResponse: t.Object({
		id: t.String(),
		cineplexChainId: t.Nullable(t.String()),
		name: t.String(),
		slug: t.String(),
		description: t.Nullable(t.String()),
		address: t.Nullable(t.String()),
		city: t.String(),
		state: t.String(),
		country: t.String(),
		phone: t.Nullable(t.String()),
		email: t.Nullable(t.String()),
		website: t.Nullable(t.String()),
		logoUrl: t.Nullable(t.String()),
		totalScreens: t.Number(),
		parkingAvailable: t.Nullable(t.Boolean()),
		wheelchairAccessible: t.Nullable(t.Boolean()),
		foodAllowed: t.Nullable(t.Boolean()),
		isActive: t.Boolean(),
	}),
	listTheatersResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			slug: t.String(),
			address: t.Nullable(t.String()),
			city: t.String(),
			totalScreens: t.Number(),
			logoUrl: t.Nullable(t.String()),
		})
	),
	listAdminTheatersResponse: t.Array(
		t.Object({
			id: t.String(),
			cineplexChainId: t.Nullable(t.String()),
			name: t.String(),
			slug: t.String(),
			description: t.Nullable(t.String()),
			address: t.Nullable(t.String()),
			city: t.String(),
			state: t.String(),
			country: t.String(),
			phone: t.Nullable(t.String()),
			email: t.Nullable(t.String()),
			website: t.Nullable(t.String()),
			logoUrl: t.Nullable(t.String()),
			totalScreens: t.Number(),
			parkingAvailable: t.Nullable(t.Boolean()),
			wheelchairAccessible: t.Nullable(t.Boolean()),
			foodAllowed: t.Nullable(t.Boolean()),
			isActive: t.Boolean(),
		})
	),
	chainResponse: t.Object({
		id: t.String(),
		name: t.String(),
		slug: t.String(),
		description: t.Nullable(t.String()),
		totalCinemas: t.Number(),
		logoUrl: t.Nullable(t.String()),
		website: t.Nullable(t.String()),
		contactEmail: t.Nullable(t.String()),
		contactPhone: t.Nullable(t.String()),
		isActive: t.Boolean(),
	}),
	listChainsResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			slug: t.String(),
			description: t.Nullable(t.String()),
			totalCinemas: t.Number(),
			logoUrl: t.Nullable(t.String()),
			website: t.Nullable(t.String()),
			contactEmail: t.Nullable(t.String()),
			contactPhone: t.Nullable(t.String()),
			isActive: t.Boolean(),
		})
	),
	screenResponse: t.Object({
		id: t.String(),
		theatreId: t.String(),
		name: t.String(),
		screenType: t.String(),
		totalSeats: t.Number(),
		isActive: t.Boolean(),
	}),
	listScreensResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			screenType: t.String(),
			totalSeats: t.Number(),
		})
	),
	listAllAdminScreensResponse: t.Array(
		t.Object({
			id: t.String(),
			theatreId: t.String(),
			name: t.String(),
			screenType: t.String(),
			totalSeats: t.Number(),
			isActive: t.Boolean(),
		})
	),
	createChainBody: t.Object({
		name: t.String(),
		slug: t.String(),
		description: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		website: t.Optional(t.String()),
		contactEmail: t.Optional(t.String()),
		contactPhone: t.Optional(t.String()),
	}),
	updateChainBody: t.Object({
		name: t.Optional(t.String()),
		slug: t.Optional(t.String()),
		description: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		website: t.Optional(t.String()),
		contactEmail: t.Optional(t.String()),
		contactPhone: t.Optional(t.String()),
		isActive: t.Optional(t.Boolean()),
	}),
	createTheaterBody: t.Object({
		cineplexChainId: t.Optional(t.String()),
		name: t.String(),
		slug: t.String(),
		description: t.Optional(t.String()),
		address: t.Optional(t.String()),
		city: t.String(),
		state: t.String(),
		phone: t.Optional(t.String()),
		email: t.Optional(t.String()),
		website: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		parkingAvailable: t.Optional(t.Boolean()),
		wheelchairAccessible: t.Optional(t.Boolean()),
		foodAllowed: t.Optional(t.Boolean()),
	}),
	updateTheaterBody: t.Object({
		cineplexChainId: t.Optional(t.Nullable(t.String())),
		name: t.Optional(t.String()),
		slug: t.Optional(t.String()),
		description: t.Optional(t.String()),
		address: t.Optional(t.String()),
		city: t.Optional(t.String()),
		state: t.Optional(t.String()),
		phone: t.Optional(t.String()),
		email: t.Optional(t.String()),
		website: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		parkingAvailable: t.Optional(t.Boolean()),
		wheelchairAccessible: t.Optional(t.Boolean()),
		foodAllowed: t.Optional(t.Boolean()),
		isActive: t.Optional(t.Boolean()),
	}),
	createScreenBody: t.Object({
		theatreId: t.String(),
		name: t.String(),
		screenType: t.Optional(t.Union([
			t.Literal('STANDARD'),
			t.Literal('IMAX'),
			t.Literal('DOLBY'),
			t.Literal('4DX'),
			t.Literal('VIP'),
			t.Literal('OTHER'),
		])),
		totalSeats: t.Number(),
	}),
	updateScreenBody: t.Object({
		name: t.Optional(t.String()),
		screenType: t.Optional(t.Union([
			t.Literal('STANDARD'),
			t.Literal('IMAX'),
			t.Literal('DOLBY'),
			t.Literal('4DX'),
			t.Literal('VIP'),
			t.Literal('OTHER'),
		])),
		totalSeats: t.Optional(t.Number()),
		isActive: t.Optional(t.Boolean()),
	}),
	errorResponse: t.Object({
		message: t.String(),
	}),
} as const

export type CinemaModel = {
	[k in keyof typeof CinemaModel]: UnwrapSchema<typeof CinemaModel[k]>
}
