import { t, type UnwrapSchema } from 'elysia'

export const CinemaModel = {
	theaterResponse: t.Object({
		id: t.String(),
		cineplexChainId: t.Nullable(t.String()),
		name: t.String(),
		slug: t.String(),
		description: t.Nullable(t.String()),
		address: t.Nullable(t.String()),
		city: t.String(),
		state: t.String(),
		country: t.String(),
		phone: t.Nullable(t.String()),
		email: t.Nullable(t.String()),
		website: t.Nullable(t.String()),
		logoUrl: t.Nullable(t.String()),
		totalScreens: t.Number(),
		parkingAvailable: t.Nullable(t.Boolean()),
		wheelchairAccessible: t.Nullable(t.Boolean()),
		foodAllowed: t.Nullable(t.Boolean()),
		isActive: t.Boolean(),
		latitude: t.Nullable(t.String()),
		longitude: t.Nullable(t.String()),
		facilities: t.Nullable(t.Array(t.String())),
		pincode: t.Nullable(t.String()),
		contactNumber: t.Nullable(t.String()),
	}),
	listTheatersResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			slug: t.String(),
			address: t.Nullable(t.String()),
			city: t.String(),
			totalScreens: t.Number(),
			logoUrl: t.Nullable(t.String()),
		})
	),
	listAdminTheatersResponse: t.Array(
		t.Object({
			id: t.String(),
			cineplexChainId: t.Nullable(t.String()),
			name: t.String(),
			slug: t.String(),
			description: t.Nullable(t.String()),
			address: t.Nullable(t.String()),
			city: t.String(),
			state: t.String(),
			country: t.String(),
			phone: t.Nullable(t.String()),
			email: t.Nullable(t.String()),
			website: t.Nullable(t.String()),
			logoUrl: t.Nullable(t.String()),
			totalScreens: t.Number(),
			parkingAvailable: t.Nullable(t.Boolean()),
			wheelchairAccessible: t.Nullable(t.Boolean()),
			foodAllowed: t.Nullable(t.Boolean()),
			isActive: t.Boolean(),
			latitude: t.Nullable(t.String()),
			longitude: t.Nullable(t.String()),
			facilities: t.Nullable(t.Array(t.String())),
			pincode: t.Nullable(t.String()),
			contactNumber: t.Nullable(t.String()),
		})
	),
	chainResponse: t.Object({
		id: t.String(),
		name: t.String(),
		slug: t.String(),
		description: t.Nullable(t.String()),
		totalCinemas: t.Number(),
		logoUrl: t.Nullable(t.String()),
		website: t.Nullable(t.String()),
		contactEmail: t.Nullable(t.String()),
		contactPhone: t.Nullable(t.String()),
		isActive: t.Boolean(),
	}),
	listChainsResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			slug: t.String(),
			description: t.Nullable(t.String()),
			totalCinemas: t.Number(),
			logoUrl: t.Nullable(t.String()),
			website: t.Nullable(t.String()),
			contactEmail: t.Nullable(t.String()),
			contactPhone: t.Nullable(t.String()),
			isActive: t.Boolean(),
		})
	),
	screenResponse: t.Object({
		id: t.String(),
		theatreId: t.String(),
		name: t.String(),
		screenType: t.String(),
		totalSeats: t.Number(),
		isActive: t.Boolean(),
		seatLayout: t.Optional(t.Nullable(t.Object({
			rows: t.Number(),
			columns: t.Number(),
			seats: t.Array(t.Object({
				row: t.String(),
				seatNumber: t.Number(),
				x: t.Number(),
				y: t.Number(),
			}))
		}))),
	}),
	listScreensResponse: t.Array(
		t.Object({
			id: t.String(),
			name: t.String(),
			screenType: t.String(),
			totalSeats: t.Number(),
		})
	),
	listAllAdminScreensResponse: t.Array(
		t.Object({
			id: t.String(),
			theatreId: t.String(),
			name: t.String(),
			screenType: t.String(),
			totalSeats: t.Number(),
			isActive: t.Boolean(),
			seatLayout: t.Optional(t.Nullable(t.Object({
				rows: t.Number(),
				columns: t.Number(),
				seats: t.Array(t.Object({
					row: t.String(),
					seatNumber: t.Number(),
					x: t.Number(),
					y: t.Number(),
				}))
			}))),
		})
	),
	createChainBody: t.Object({
		name: t.String(),
		slug: t.String(),
		description: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		website: t.Optional(t.String()),
		contactEmail: t.Optional(t.String()),
		contactPhone: t.Optional(t.String()),
	}),
	updateChainBody: t.Object({
		name: t.Optional(t.String()),
		slug: t.Optional(t.String()),
		description: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		website: t.Optional(t.String()),
		contactEmail: t.Optional(t.String()),
		contactPhone: t.Optional(t.String()),
		isActive: t.Optional(t.Boolean()),
	}),
	createTheaterBody: t.Object({
		cineplexChainId: t.Optional(t.String()),
		name: t.String(),
		slug: t.String(),
		description: t.Optional(t.String()),
		address: t.Optional(t.String()),
		city: t.String(),
		state: t.String(),
		phone: t.Optional(t.String()),
		email: t.Optional(t.String()),
		website: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		parkingAvailable: t.Optional(t.Boolean()),
		wheelchairAccessible: t.Optional(t.Boolean()),
		foodAllowed: t.Optional(t.Boolean()),
		latitude: t.Optional(t.String()),
		longitude: t.Optional(t.String()),
		facilities: t.Optional(t.Array(t.String())),
		pincode: t.Optional(t.String()),
		country: t.Optional(t.String()),
		contactNumber: t.Optional(t.String()),
	}),
	updateTheaterBody: t.Object({
		cineplexChainId: t.Optional(t.Nullable(t.String())),
		name: t.Optional(t.String()),
		slug: t.Optional(t.String()),
		description: t.Optional(t.String()),
		address: t.Optional(t.String()),
		city: t.Optional(t.String()),
		state: t.Optional(t.String()),
		phone: t.Optional(t.String()),
		email: t.Optional(t.String()),
		website: t.Optional(t.String()),
		logoUrl: t.Optional(t.String()),
		parkingAvailable: t.Optional(t.Boolean()),
		wheelchairAccessible: t.Optional(t.Boolean()),
		foodAllowed: t.Optional(t.Boolean()),
		isActive: t.Optional(t.Boolean()),
		latitude: t.Optional(t.Nullable(t.String())),
		longitude: t.Optional(t.Nullable(t.String())),
		facilities: t.Optional(t.Nullable(t.Array(t.String()))),
		pincode: t.Optional(t.Nullable(t.String())),
		country: t.Optional(t.String()),
		contactNumber: t.Optional(t.Nullable(t.String())),
	}),
	createScreenBody: t.Object({
		theatreId: t.String(),
		name: t.String(),
		screenType: t.Optional(t.Union([
			t.Literal('STANDARD'),
			t.Literal('IMAX'),
			t.Literal('DOLBY'),
			t.Literal('4DX'),
			t.Literal('VIP'),
			t.Literal('OTHER'),
		])),
		totalSeats: t.Number(),
	}),
	updateScreenBody: t.Object({
		name: t.Optional(t.String()),
		screenType: t.Optional(t.Union([
			t.Literal('STANDARD'),
			t.Literal('IMAX'),
			t.Literal('DOLBY'),
			t.Literal('4DX'),
			t.Literal('VIP'),
			t.Literal('OTHER'),
		])),
		totalSeats: t.Optional(t.Number()),
		isActive: t.Optional(t.Boolean()),
		seatLayout: t.Optional(t.Object({
			rows: t.Number(),
			columns: t.Number(),
			seats: t.Array(t.Object({
				row: t.String(),
				seatNumber: t.Number(),
				x: t.Number(),
				y: t.Number(),
			}))
		})),
	}),
	paginatedChainsResponse: t.Object({
		items: t.Array(
			t.Object({
				id: t.String(),
				name: t.String(),
				slug: t.String(),
				description: t.Nullable(t.String()),
				totalCinemas: t.Number(),
				logoUrl: t.Nullable(t.String()),
				website: t.Nullable(t.String()),
				contactEmail: t.Nullable(t.String()),
				contactPhone: t.Nullable(t.String()),
				isActive: t.Boolean(),
			})
		),
		total: t.Number(),
		page: t.Number(),
		limit: t.Number(),
		pages: t.Number(),
	}),
	paginatedAdminTheatersResponse: t.Object({
		items: t.Array(
			t.Object({
				id: t.String(),
				cineplexChainId: t.Nullable(t.String()),
				name: t.String(),
				slug: t.String(),
				description: t.Nullable(t.String()),
				address: t.Nullable(t.String()),
				city: t.String(),
				state: t.String(),
				country: t.String(),
				phone: t.Nullable(t.String()),
				email: t.Nullable(t.String()),
				website: t.Nullable(t.String()),
				logoUrl: t.Nullable(t.String()),
				totalScreens: t.Number(),
				parkingAvailable: t.Nullable(t.Boolean()),
				wheelchairAccessible: t.Nullable(t.Boolean()),
				foodAllowed: t.Nullable(t.Boolean()),
				isActive: t.Boolean(),
				latitude: t.Nullable(t.String()),
				longitude: t.Nullable(t.String()),
				facilities: t.Nullable(t.Array(t.String())),
				pincode: t.Nullable(t.String()),
				contactNumber: t.Nullable(t.String()),
			})
		),
		total: t.Number(),
		page: t.Number(),
		limit: t.Number(),
		pages: t.Number(),
	}),
	paginatedAllAdminScreensResponse: t.Object({
		items: t.Array(
			t.Object({
				id: t.String(),
				theatreId: t.String(),
				name: t.String(),
				screenType: t.String(),
				totalSeats: t.Number(),
				isActive: t.Boolean(),
				seatLayout: t.Optional(t.Nullable(t.Object({
					rows: t.Number(),
					columns: t.Number(),
					seats: t.Array(t.Object({
						row: t.String(),
						seatNumber: t.Number(),
						x: t.Number(),
						y: t.Number(),
					}))
				}))),
			})
		),
		total: t.Number(),
		page: t.Number(),
		limit: t.Number(),
		pages: t.Number(),
	}),
	paginationQuery: t.Object({
		page: t.Optional(t.Numeric()),
		limit: t.Optional(t.Numeric()),
		search: t.Optional(t.String()),
	}),
	theaterQuery: t.Object({
		page: t.Optional(t.Numeric()),
		limit: t.Optional(t.Numeric()),
		search: t.Optional(t.String()),
		cineplexChainId: t.Optional(t.String()),
		city: t.Optional(t.String()),
		isActive: t.Optional(t.String()),
	}),

	screenQuery: t.Object({
		page: t.Optional(t.Numeric()),
		limit: t.Optional(t.Numeric()),
		search: t.Optional(t.String()),
		cineplexChainId: t.Optional(t.String()),
		theatreId: t.Optional(t.String()),
	}),
	errorResponse: t.Object({
		message: t.String(),
	}),
} as const

export type CinemaModel = {
	[k in keyof typeof CinemaModel]: UnwrapSchema<typeof CinemaModel[k]>
}
